# Generated by hyperi-rustlib deployment module
# Do not edit manually — regenerate from DeploymentContract
#
# License:   FSL-1.1-ALv2
# Copyright: (c) 2026 HYPERI PTY LIMITED

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl netcat-openbsd iputils-ping \
    && rm -rf /var/lib/apt/lists/*

COPY dfe-fetcher /usr/local/bin/dfe-fetcher
RUN chmod +x /usr/local/bin/dfe-fetcher

RUN useradd --create-home --uid 1000 appuser
USER appuser

EXPOSE 9090 8080 6000

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -sf http://localhost:9090/health/live > /dev/null || exit 1

ENTRYPOINT ["dfe-fetcher"]
CMD ["--config", "/etc/dfe/fetcher.yaml"]

