# Project:   dfe-fetcher
# File:      Dockerfile
# Purpose:   production container image
#
# License:   FSL-1.1-ALv2
# Copyright: (c) 2026 HYPERI PTY LIMITED
#
# AUTOGENERATED — do not edit by hand.
# Generated by hyperi-rustlib::deployment::generate_dockerfile()
# Schema version: 2
# Source contract: dfe-fetcher::deployment::contract()
# Regenerate with: `dfe-fetcher emit-dockerfile > Dockerfile`

FROM ubuntu:26.04

LABEL io.hyperi.profile="production"

# Runtime shared libraries for dynamically-linked Rust crates.
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl netcat-openbsd iputils-ping gnupg \
    && curl -fsSL https://packages.confluent.io/clients/deb/archive.key \
       | gpg --dearmor -o /usr/share/keyrings/confluent-clients.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/confluent-clients.gpg] \
       https://packages.confluent.io/clients/deb noble main" \
       > /etc/apt/sources.list.d/confluent-clients.list \
    && apt-get update && apt-get install -y --no-install-recommends \
       librdkafka1 libssl3 zlib1g libzstd1 \
    && rm -rf /var/lib/apt/lists/*

COPY dfe-fetcher /usr/local/bin/dfe-fetcher
RUN chmod +x /usr/local/bin/dfe-fetcher

# Ubuntu 24.04 ships with ubuntu user at UID 1000 — remove before creating appuser
RUN userdel -r ubuntu && useradd --create-home --uid 1000 appuser
USER appuser

EXPOSE 9090 8080 6000

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -sf http://localhost:9090/health/live > /dev/null || exit 1

ENTRYPOINT ["dfe-fetcher"]
CMD ["--config", "/etc/dfe/fetcher.yaml"]

