apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dfe-fetcher.fullname" . }}-config
  labels:
    {{- include "dfe-fetcher.labels" . | nindent 4 }}
data:
  fetcher.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
