{{- if not .Values.kafka.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfe-fetcher.kafkaSecretName" . }}
  labels:
    {{- include "dfe-fetcher.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.kafka.secretKeys.username }}: {{ .Values.kafka.username | b64enc | quote }}
  {{ .Values.kafka.secretKeys.password }}: {{ .Values.kafka.password | b64enc | quote }}
{{- end }}
---
{{- if not .Values.aws.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfe-fetcher.awsSecretName" . }}
  labels:
    {{- include "dfe-fetcher.labels" . | nindent 4 }}
type: Opaque
data:
  {{ (index .Values.aws.secretKeys "access-key-id") }}: {{ (index .Values.aws "access-key-id") | b64enc | quote }}
  {{ (index .Values.aws.secretKeys "secret-access-key") }}: {{ (index .Values.aws "secret-access-key") | b64enc | quote }}
{{- end }}
---
{{- if not .Values.azure.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfe-fetcher.azureSecretName" . }}
  labels:
    {{- include "dfe-fetcher.labels" . | nindent 4 }}
type: Opaque
data:
  {{ (index .Values.azure.secretKeys "client-id") }}: {{ (index .Values.azure "client-id") | b64enc | quote }}
  {{ (index .Values.azure.secretKeys "client-secret") }}: {{ (index .Values.azure "client-secret") | b64enc | quote }}
{{- end }}
---
{{- if not .Values.m365.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfe-fetcher.m365SecretName" . }}
  labels:
    {{- include "dfe-fetcher.labels" . | nindent 4 }}
type: Opaque
data:
  {{ (index .Values.m365.secretKeys "client-id") }}: {{ (index .Values.m365 "client-id") | b64enc | quote }}
  {{ (index .Values.m365.secretKeys "client-secret") }}: {{ (index .Values.m365 "client-secret") | b64enc | quote }}
{{- end }}
---
{{- if not .Values.gcp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfe-fetcher.gcpSecretName" . }}
  labels:
    {{- include "dfe-fetcher.labels" . | nindent 4 }}
type: Opaque
data:
  {{ (index .Values.gcp.secretKeys "service-account-key") }}: {{ (index .Values.gcp "service-account-key") | b64enc | quote }}
{{- end }}
