apiVersion: v1
kind: Service
metadata:
  name: {{ include "dfe-fetcher.fullname" . }}
  labels:
    {{- include "dfe-fetcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: ingest
    - port: 6000
      targetPort: 6000
      protocol: TCP
      name: vector-grpc
  selector:
    {{- include "dfe-fetcher.selectorLabels" . | nindent 4 }}
