// Project:   dfe-fetcher
// File:      tests/e2e/smoke_cloud.rs
// Purpose:   Live cloud API smoke tests (requires real credentials in .env)
// Language:  Rust
//
// License:   FSL-1.1-ALv2
// Copyright: (c) 2026 HYPERI PTY LIMITED

//! Smoke tests against real cloud APIs.
//!
//! These tests are `#[ignore]`d by default because they require real credentials.
//! Run with:
//!
//! ```bash
//! cargo test --test e2e -- --ignored
//! ```
//!
//! Credentials are loaded from `.env` at the project root (generated by
//! `infra/test/gen-env.py` from Terraform outputs).

use std::collections::HashMap;

use dfe_fetcher::config::{AwsService, AwsSourceConfig, AzureService, AzureSourceConfig};
use dfe_fetcher::config::{GcpService, GcpSourceConfig};
use dfe_fetcher::source::Source;
use dfe_fetcher::source::aws::AwsSource;
use dfe_fetcher::source::azure::AzureSource;
use dfe_fetcher::source::gcp::GcpSource;

/// Load .env file, overriding any existing env vars (e.g. stale credentials
/// from previous sessions). Panics if .env is missing (test requires credentials).
fn load_env() {
    dotenvy::dotenv_override().ok();
}

fn env(key: &str) -> Option<String> {
    std::env::var(key).ok().filter(|v| !v.is_empty())
}

// =============================================================================
// AWS — SigV4 signing against real CloudTrail
// =============================================================================

fn make_aws_config() -> Option<AwsSourceConfig> {
    let access_key_id = env("AWS_ACCESS_KEY_ID")?;
    let secret_access_key = env("AWS_SECRET_ACCESS_KEY")?;
    let region = env("AWS_REGION").unwrap_or_else(|| "ap-southeast-2".to_string());

    Some(AwsSourceConfig {
        enabled: true,
        region,
        access_key_id: Some(access_key_id),
        secret_access_key: Some(secret_access_key),
        assume_role_arn: None,
        credential_secret: None,
        endpoint_override: None,
        interval_secs: None,
        services: vec![AwsService {
            name: "cloudtrail".to_string(),
            config: HashMap::new(),
        }],
        topic: "test-aws".to_string(),
        filter: None,
    })
}

#[tokio::test]
#[ignore = "requires live cloud credentials"]
async fn aws_health_check() {
    load_env();
    let config = make_aws_config().expect("AWS credentials not found in .env");
    let source = AwsSource::new(config);

    let healthy = source.health_check().await.expect("health_check failed");
    assert!(
        healthy,
        "AWS health check should pass with valid credentials"
    );
}

#[tokio::test]
#[ignore = "requires live cloud credentials"]
async fn aws_fetch_cloudtrail() {
    load_env();
    let config = make_aws_config().expect("AWS credentials not found in .env");
    let source = AwsSource::new(config);

    let results = source.fetch(None).await.expect("fetch failed");
    // CloudTrail may return empty if no recent events, but must not error
    eprintln!(
        "AWS CloudTrail: {} result(s), {} total records",
        results.len(),
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

fn make_aws_cloudwatch_logs_config() -> Option<AwsSourceConfig> {
    let access_key_id = env("AWS_ACCESS_KEY_ID")?;
    let secret_access_key = env("AWS_SECRET_ACCESS_KEY")?;
    let region = env("AWS_REGION").unwrap_or_else(|| "ap-southeast-2".to_string());

    // Use a log group from env, or discover the first available one
    let log_group = env("AWS_CLOUDWATCH_LOG_GROUP").unwrap_or_else(|| "vpc_flow_logs".to_string());

    let mut svc_config = HashMap::new();
    svc_config.insert(
        "log_group_name".to_string(),
        serde_json::Value::String(log_group),
    );

    Some(AwsSourceConfig {
        enabled: true,
        region,
        access_key_id: Some(access_key_id),
        secret_access_key: Some(secret_access_key),
        assume_role_arn: None,
        credential_secret: None,
        endpoint_override: None,
        interval_secs: None,
        services: vec![AwsService {
            name: "cloudwatch_logs".to_string(),
            config: svc_config,
        }],
        topic: "test-aws".to_string(),
        filter: None,
    })
}

#[tokio::test]
#[ignore = "requires live cloud credentials"]
async fn aws_fetch_cloudwatch_logs() {
    load_env();
    let config = make_aws_cloudwatch_logs_config().expect("AWS credentials not found in .env");
    let source = AwsSource::new(config);

    let results = source.fetch(None).await.expect("fetch failed");
    eprintln!(
        "AWS CloudWatch Logs: {} result(s), {} total records",
        results.len(),
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

fn make_aws_cloudwatch_metrics_config() -> Option<AwsSourceConfig> {
    let access_key_id = env("AWS_ACCESS_KEY_ID")?;
    let secret_access_key = env("AWS_SECRET_ACCESS_KEY")?;
    let region = env("AWS_REGION").unwrap_or_else(|| "ap-southeast-2".to_string());

    let mut svc_config = HashMap::new();
    svc_config.insert("namespaces".to_string(), serde_json::json!(["AWS/EC2"]));

    Some(AwsSourceConfig {
        enabled: true,
        region,
        access_key_id: Some(access_key_id),
        secret_access_key: Some(secret_access_key),
        assume_role_arn: None,
        credential_secret: None,
        endpoint_override: None,
        interval_secs: None,
        services: vec![AwsService {
            name: "cloudwatch_metrics".to_string(),
            config: svc_config,
        }],
        topic: "test-aws".to_string(),
        filter: None,
    })
}

#[tokio::test]
#[ignore = "requires live cloud credentials"]
async fn aws_fetch_cloudwatch_metrics() {
    load_env();
    let config = make_aws_cloudwatch_metrics_config().expect("AWS credentials not found in .env");
    let source = AwsSource::new(config);

    let results = source.fetch(None).await.expect("fetch failed");
    eprintln!(
        "AWS CloudWatch Metrics: {} result(s), {} total records",
        results.len(),
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// Azure — OAuth2 client_credentials against real Activity Log
// =============================================================================

fn make_azure_config() -> Option<AzureSourceConfig> {
    let tenant_id = env("AZURE_TENANT_ID")?;
    let client_id = env("AZURE_CLIENT_ID")?;
    let client_secret = env("AZURE_CLIENT_SECRET")?;
    let subscription_id = env("AZURE_SUBSCRIPTION_ID")?;

    Some(AzureSourceConfig {
        enabled: true,
        tenant_id: Some(tenant_id),
        client_id: Some(client_id),
        client_secret: Some(client_secret),
        credential_secret: None,
        subscription_id: Some(subscription_id),
        management_url_override: None,
        graph_url_override: None,
        token_url_override: None,
        interval_secs: None,
        services: vec![AzureService {
            name: "activity_log".to_string(),
            config: HashMap::new(),
        }],
        topic: "test-azure".to_string(),
        filter: None,
    })
}

#[tokio::test]
#[ignore = "requires live cloud credentials"]
async fn azure_health_check() {
    load_env();
    let config = make_azure_config().expect("Azure credentials not found in .env");
    let source = AzureSource::new(config);

    let healthy = source.health_check().await.expect("health_check failed");
    assert!(
        healthy,
        "Azure health check should pass with valid credentials"
    );
}

#[tokio::test]
#[ignore = "requires live cloud credentials"]
async fn azure_fetch_activity_log() {
    load_env();
    let config = make_azure_config().expect("Azure credentials not found in .env");
    let source = AzureSource::new(config);

    let results = source.fetch(None).await.expect("fetch failed");
    eprintln!(
        "Azure Activity Log: {} result(s), {} total records",
        results.len(),
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// GCP — JWT signing against real Cloud Logging
// =============================================================================

fn make_gcp_config() -> Option<GcpSourceConfig> {
    let project_id = env("GCP_PROJECT_ID")?;
    let key_path = env("GCP_SERVICE_ACCOUNT_KEY")?;

    // Verify key file exists
    if !std::path::Path::new(&key_path).exists() {
        eprintln!("GCP key file not found: {key_path}");
        return None;
    }

    Some(GcpSourceConfig {
        enabled: true,
        project_id: Some(project_id),
        service_account_key: Some(key_path),
        credential_secret: None,
        api_url_override: None,
        token_url_override: None,
        interval_secs: None,
        services: vec![GcpService {
            name: "cloud_logging".to_string(),
            config: HashMap::new(),
        }],
        topic: "test-gcp".to_string(),
        filter: None,
    })
}

#[tokio::test]
#[ignore = "requires live cloud credentials"]
async fn gcp_health_check() {
    load_env();
    let Some(config) = make_gcp_config() else {
        eprintln!("Skipping GCP: credentials not available");
        return;
    };
    let source = GcpSource::new(config);

    let healthy = source.health_check().await.expect("health_check failed");
    assert!(
        healthy,
        "GCP health check should pass with valid credentials"
    );
}

#[tokio::test]
#[ignore = "requires live cloud credentials"]
async fn gcp_fetch_cloud_logging() {
    load_env();
    let Some(config) = make_gcp_config() else {
        eprintln!("Skipping GCP: credentials not available");
        return;
    };
    let source = GcpSource::new(config);

    let results = source.fetch(None).await.expect("fetch failed");
    eprintln!(
        "GCP Cloud Logging: {} result(s), {} total records",
        results.len(),
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}
