// Project:   dfe-fetcher
// File:      tests/e2e/smoke_remote.rs
// Purpose:   Live remote-source smoke tests (cloud APIs + SaaS audit logs)
// Language:  Rust
//
// License:   FSL-1.1-ALv2
// Copyright: (c) 2026 HYPERI PTY LIMITED

//! Live remote-source smoke tests against real tenants / SaaS accounts.
//!
//! Covers AWS, Azure, M365, GCP (cloud APIs) plus GitHub audit (SaaS). All
//! tests are `#[ignore]`d so they don't run on every push. To run them:
//!
//! ```bash
//! cargo nextest run --test e2e -- --ignored
//! # or filter to one source family:
//! cargo nextest run --test e2e -- --ignored github_
//! ```
//!
//! Credentials are loaded from `.env-cloud` (canonical, generated by
//! `infra/test/gen-env.py` from `kv/dfe-test/*`) with a fallback to `.env`.
//! Each test panics with a clear message if its required env vars are
//! missing -- no more silent skips that pretend to pass.
//!
//! ## Credential reuse
//!
//! `.env-cloud` does not carry separate `M365_*` variables. M365 IS Entra/
//! Azure AD: the `dfe-fetcher-azure-test` SP in the HyperI MS tenant has
//! both Azure Management and Microsoft Graph permissions granted, so the
//! M365 tests reuse `AZURE_TENANT_ID`/`AZURE_CLIENT_ID`/`AZURE_CLIENT_SECRET`.
//!
//! ## Per-service isolation
//!
//! Each test exercises ONE service (`Source::fetch` aggregates across all
//! configured services and swallows errors, which previously masked broken
//! services as "passing"). Coverage is per-service so a regression in one
//! surface fails its own test.

use std::collections::HashMap;

use dfe_fetcher::config::{
    AwsService, AwsSourceConfig, AzureService, AzureSourceConfig, BitwardenService,
    BitwardenSourceConfig, CloudflareService, CloudflareSourceConfig, CratesIoSourceConfig,
    CrowdstrikeService, CrowdstrikeSourceConfig, DuoService, DuoSourceConfig,
    GcpPubsubSourceConfig, GcpPubsubSubscription, GcpService, GcpSourceConfig, GithubService,
    GithubSourceConfig, GoModulesSourceConfig, GoogleWorkspaceService, GoogleWorkspaceSourceConfig,
    M365Service, M365SourceConfig, ObjectStoreBackendConfig, ObjectStoreBucket, ObjectStoreFormat,
    ObjectStorePrefix, ObjectStoreSourceConfig, OktaService, OktaSourceConfig, OnePasswordService,
    OnePasswordSourceConfig, PypiSourceConfig, S3BackendConfig, SalesforceService,
    SalesforceSourceConfig, SlackService, SlackSourceConfig,
};
use dfe_fetcher::source::Source;
use dfe_fetcher::source::aws::AwsSource;
use dfe_fetcher::source::azure::AzureSource;
use dfe_fetcher::source::bitwarden::BitwardenSource;
use dfe_fetcher::source::cloudflare::CloudflareSource;
use dfe_fetcher::source::crates_io::CratesIoSource;
use dfe_fetcher::source::crowdstrike::CrowdstrikeSource;
use dfe_fetcher::source::duo::DuoSource;
use dfe_fetcher::source::gcp::GcpSource;
use dfe_fetcher::source::gcp_pubsub::GcpPubsubSource;
use dfe_fetcher::source::github::GithubSource;
use dfe_fetcher::source::go_modules::GoModulesSource;
use dfe_fetcher::source::google_workspace::GoogleWorkspaceSource;
use dfe_fetcher::source::m365::M365Source;
use dfe_fetcher::source::object_store::ObjectStoreSource;
use dfe_fetcher::source::okta::OktaSource;
use dfe_fetcher::source::onepassword::OnePasswordSource;
use dfe_fetcher::source::pypi::PypiSource;
use dfe_fetcher::source::salesforce::SalesforceSource;
use dfe_fetcher::source::slack::SlackSource;

// =============================================================================
// Env loading: .env-cloud is canonical, .env is fallback
// =============================================================================

/// Load cloud credentials from `.env-cloud` (preferred) or `.env` (fallback).
/// `dotenvy::from_filename_override` replaces any existing env vars so stale
/// values from a previous session can't leak through.
fn load_env() {
    let _ = dotenvy::from_filename_override(".env-cloud");
    let _ = dotenvy::dotenv_override();
}

fn require(key: &str) -> String {
    std::env::var(key)
        .ok()
        .filter(|v| !v.is_empty())
        .unwrap_or_else(|| panic!("missing required env var {key} (check .env-cloud)"))
}

fn optional(key: &str) -> Option<String> {
    std::env::var(key).ok().filter(|v| !v.is_empty())
}

// =============================================================================
// AWS -- SigV4 against real CloudTrail / CloudWatch
// =============================================================================

fn aws_base() -> AwsSourceConfig {
    AwsSourceConfig {
        enabled: true,
        region: optional("AWS_REGION").unwrap_or_else(|| "ap-southeast-2".to_string()),
        access_key_id: Some(require("AWS_ACCESS_KEY_ID")),
        secret_access_key: Some(require("AWS_SECRET_ACCESS_KEY").into()),
        assume_role_arn: None,
        credential_secret: None,
        endpoint_override: None,
        interval_secs: None,
        services: vec![],
        topic: "test-aws".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live AWS credentials"]
async fn aws_health_check() {
    load_env();
    let mut cfg = aws_base();
    cfg.services.push(AwsService {
        name: "cloudtrail".to_string(),
        config: HashMap::new(),
    });
    let source = AwsSource::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("AWS health_check errored");
    assert!(healthy, "AWS health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live AWS credentials"]
async fn aws_fetch_cloudtrail() {
    load_env();
    let mut cfg = aws_base();
    cfg.services.push(AwsService {
        name: "cloudtrail".to_string(),
        config: HashMap::new(),
    });
    let source = AwsSource::new(cfg);
    let results = source.fetch(None).await.expect("CloudTrail fetch failed");
    eprintln!(
        "AWS CloudTrail: {} result(s), {} total records",
        results.len(),
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

#[tokio::test]
#[ignore = "requires live AWS credentials"]
async fn aws_fetch_cloudwatch_logs() {
    load_env();
    let log_group = optional("AWS_CLOUDWATCH_LOG_GROUP").unwrap_or_else(|| "vpc_flow_logs".into());
    let mut svc_config = HashMap::new();
    svc_config.insert(
        "log_group_name".into(),
        serde_json::Value::String(log_group),
    );

    let mut cfg = aws_base();
    cfg.services.push(AwsService {
        name: "cloudwatch_logs".to_string(),
        config: svc_config,
    });
    let source = AwsSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("CloudWatch Logs fetch failed");
    eprintln!(
        "AWS CloudWatch Logs: {} result(s), {} total records",
        results.len(),
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

#[tokio::test]
#[ignore = "requires live AWS credentials"]
async fn aws_fetch_cloudwatch_metrics() {
    load_env();
    let mut svc_config = HashMap::new();
    svc_config.insert("namespaces".into(), serde_json::json!(["AWS/EC2"]));

    let mut cfg = aws_base();
    cfg.services.push(AwsService {
        name: "cloudwatch_metrics".to_string(),
        config: svc_config,
    });
    let source = AwsSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("CloudWatch Metrics fetch failed");
    eprintln!(
        "AWS CloudWatch Metrics: {} result(s), {} total records",
        results.len(),
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// `inspector` -- requires tenant to have Inspector v2 enabled. Zero records
/// is the normal state on a test account with no scan-able resources.
#[tokio::test]
#[ignore = "requires live AWS credentials AND Inspector v2 enabled on tenant"]
async fn aws_fetch_inspector() {
    load_env();
    let mut cfg = aws_base();
    cfg.services.push(AwsService {
        name: "inspector".to_string(),
        config: HashMap::new(),
    });
    let source = AwsSource::new(cfg);
    let results = source.fetch(None).await.expect("Inspector fetch failed");
    for r in &results {
        assert_eq!(r.source, "aws.inspector");
    }
    eprintln!(
        "AWS Inspector: {} record(s) (zero may indicate Inspector v2 \
         not enabled or no scan-able resources)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// `health` -- requires Business / Enterprise On-Ramp / Enterprise support
/// tier on the AWS account; lesser tiers return AccessDeniedException.
#[tokio::test]
#[ignore = "requires live AWS credentials AND Business+ support tier"]
async fn aws_fetch_health() {
    load_env();
    let mut cfg = aws_base();
    cfg.services.push(AwsService {
        name: "health".to_string(),
        config: HashMap::new(),
    });
    let source = AwsSource::new(cfg);
    let results = source.fetch(None).await.expect("Health fetch failed");
    for r in &results {
        assert_eq!(r.source, "aws.health");
    }
    eprintln!(
        "AWS Health: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// Azure -- OAuth2 client_credentials against real Activity Log / Sentinel
// =============================================================================

fn azure_base() -> AzureSourceConfig {
    AzureSourceConfig {
        enabled: true,
        tenant_id: Some(require("AZURE_TENANT_ID")),
        client_id: Some(require("AZURE_CLIENT_ID")),
        client_secret: Some(require("AZURE_CLIENT_SECRET").into()),
        credential_secret: None,
        subscription_id: Some(require("AZURE_SUBSCRIPTION_ID")),
        management_url_override: None,
        graph_url_override: None,
        token_url_override: None,
        interval_secs: None,
        services: vec![],
        topic: "test-azure".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live Azure credentials"]
async fn azure_health_check() {
    load_env();
    let mut cfg = azure_base();
    cfg.services.push(AzureService {
        name: "activity_log".to_string(),
        config: HashMap::new(),
    });
    let source = AzureSource::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("Azure health_check errored");
    assert!(healthy, "Azure health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live Azure credentials"]
async fn azure_fetch_activity_log() {
    load_env();
    let mut cfg = azure_base();
    cfg.services.push(AzureService {
        name: "activity_log".to_string(),
        config: HashMap::new(),
    });
    let source = AzureSource::new(cfg);
    let results = source.fetch(None).await.expect("Activity Log fetch failed");
    eprintln!(
        "Azure Activity Log: {} result(s), {} total records",
        results.len(),
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// New split: `entra_signins` emits its own FetchResult tagged
/// `azure.entra_signins`.
#[tokio::test]
#[ignore = "requires live Azure credentials"]
async fn azure_fetch_entra_signins() {
    load_env();
    let mut cfg = azure_base();
    cfg.services.push(AzureService {
        name: "entra_signins".to_string(),
        config: HashMap::new(),
    });
    let source = AzureSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("entra_signins fetch failed");
    for r in &results {
        assert_eq!(r.source, "azure.entra_signins");
    }
    eprintln!(
        "Azure entra_signins: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// New split: `entra_directory_audits` emits its own FetchResult tagged
/// `azure.entra_directory_audits`.
#[tokio::test]
#[ignore = "requires live Azure credentials"]
async fn azure_fetch_entra_directory_audits() {
    load_env();
    let mut cfg = azure_base();
    cfg.services.push(AzureService {
        name: "entra_directory_audits".to_string(),
        config: HashMap::new(),
    });
    let source = AzureSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("entra_directory_audits fetch failed");
    for r in &results {
        assert_eq!(r.source, "azure.entra_directory_audits");
    }
    eprintln!(
        "Azure entra_directory_audits: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// New split: `entra_provisioning` emits its own FetchResult tagged
/// `azure.entra_provisioning`. May 403 if the SP lacks the provisioning
/// scope - that's the failure signal we want (loud, not silent).
#[tokio::test]
#[ignore = "requires live Azure credentials AND provisioning scope on the SP"]
async fn azure_fetch_entra_provisioning() {
    load_env();
    let mut cfg = azure_base();
    cfg.services.push(AzureService {
        name: "entra_provisioning".to_string(),
        config: HashMap::new(),
    });
    let source = AzureSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("entra_provisioning fetch failed");
    for r in &results {
        assert_eq!(r.source, "azure.entra_provisioning");
    }
    eprintln!(
        "Azure entra_provisioning: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// `log_analytics` -- runs a KQL query against an existing workspace.
/// Requires the workspace ID (GUID, NOT customer-facing name) and a KQL
/// query in service config. Tenant requirement: the SP must have the
/// `Log Analytics Reader` role on the workspace.
#[tokio::test]
#[ignore = "requires live Azure credentials AND Log Analytics workspace with data"]
async fn azure_fetch_log_analytics() {
    load_env();
    let workspace_id = require("AZURE_LOG_ANALYTICS_WORKSPACE_ID");
    let kql =
        optional("AZURE_LOG_ANALYTICS_KQL").unwrap_or_else(|| "Heartbeat | take 10".to_string());

    let mut svc_config = HashMap::new();
    svc_config.insert(
        "workspace_id".into(),
        serde_json::Value::String(workspace_id),
    );
    svc_config.insert("kql".into(), serde_json::Value::String(kql));

    let mut cfg = azure_base();
    cfg.services.push(AzureService {
        name: "log_analytics".to_string(),
        config: svc_config,
    });
    let source = AzureSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("log_analytics fetch failed");
    for r in &results {
        assert_eq!(r.source, "azure.log_analytics");
    }
    eprintln!(
        "Azure log_analytics: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

#[tokio::test]
#[ignore = "requires live Azure credentials"]
async fn azure_fetch_sentinel() {
    load_env();
    let workspace = require("AZURE_SENTINEL_WORKSPACE_NAME");
    let resource_group = require("AZURE_SENTINEL_RESOURCE_GROUP");
    let mut svc_config = HashMap::new();
    svc_config.insert(
        "workspace_name".into(),
        serde_json::Value::String(workspace),
    );
    svc_config.insert(
        "resource_group".into(),
        serde_json::Value::String(resource_group),
    );

    let mut cfg = azure_base();
    cfg.services.push(AzureService {
        name: "sentinel".to_string(),
        config: svc_config,
    });
    let source = AzureSource::new(cfg);
    let results = source.fetch(None).await.expect("Sentinel fetch failed");
    eprintln!(
        "Azure Sentinel: {} result(s), {} total records",
        results.len(),
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// GCP -- JWT signing against real Cloud Logging
// =============================================================================

fn gcp_base() -> GcpSourceConfig {
    let key_path = require("GCP_SERVICE_ACCOUNT_KEY");
    assert!(
        std::path::Path::new(&key_path).exists(),
        "GCP service account key file not found at {key_path}"
    );
    GcpSourceConfig {
        enabled: true,
        project_id: Some(require("GCP_PROJECT_ID")),
        service_account_key: Some(key_path),
        credential_secret: None,
        api_url_override: None,
        token_url_override: None,
        interval_secs: None,
        services: vec![],
        topic: "test-gcp".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live GCP credentials"]
async fn gcp_health_check() {
    load_env();
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: "cloud_logging".to_string(),
        config: HashMap::new(),
    });
    let source = GcpSource::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("GCP health_check errored");
    assert!(healthy, "GCP health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live GCP credentials"]
async fn gcp_fetch_cloud_logging() {
    load_env();
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: "cloud_logging".to_string(),
        config: HashMap::new(),
    });
    let source = GcpSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("Cloud Logging fetch failed");
    eprintln!(
        "GCP Cloud Logging: {} result(s), {} total records",
        results.len(),
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// New split: `admin_activity` -- ON by default in every GCP project. Should
/// always return records on a tenant with any activity.
#[tokio::test]
#[ignore = "requires live GCP credentials"]
async fn gcp_fetch_admin_activity() {
    load_env();
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: "admin_activity".to_string(),
        config: HashMap::new(),
    });
    let source = GcpSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("admin_activity fetch failed");
    for r in &results {
        assert_eq!(r.source, "gcp.admin_activity");
    }
    eprintln!(
        "GCP admin_activity: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// New split: `data_access` -- OFF by default in GCP projects. Returning
/// zero records here may indicate the tenant has not enabled Data Access
/// audit logs (separate hyperi-infra issue). Test still PASSES on zero
/// records to avoid false failures.
#[tokio::test]
#[ignore = "requires live GCP credentials AND Data Access audit enabled on tenant"]
async fn gcp_fetch_data_access() {
    load_env();
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: "data_access".to_string(),
        config: HashMap::new(),
    });
    let source = GcpSource::new(cfg);
    let results = source.fetch(None).await.expect("data_access fetch failed");
    for r in &results {
        assert_eq!(r.source, "gcp.data_access");
    }
    eprintln!(
        "GCP data_access: {} record(s) (zero may indicate tenant has not \
         enabled Data Access audit logs)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// New split: `system_event` -- Google-system-driven actions. Volume is
/// usually low but non-zero on any active project.
#[tokio::test]
#[ignore = "requires live GCP credentials"]
async fn gcp_fetch_system_event() {
    load_env();
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: "system_event".to_string(),
        config: HashMap::new(),
    });
    let source = GcpSource::new(cfg);
    let results = source.fetch(None).await.expect("system_event fetch failed");
    for r in &results {
        assert_eq!(r.source, "gcp.system_event");
    }
    eprintln!(
        "GCP system_event: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// New split: `policy_denied` -- VPC SC and other policy violations. Zero
/// records on a tenant with no policy violations is the normal case.
#[tokio::test]
#[ignore = "requires live GCP credentials"]
async fn gcp_fetch_policy_denied() {
    load_env();
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: "policy_denied".to_string(),
        config: HashMap::new(),
    });
    let source = GcpSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("policy_denied fetch failed");
    for r in &results {
        assert_eq!(r.source, "gcp.policy_denied");
    }
    eprintln!(
        "GCP policy_denied: {} record(s) (zero is normal)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// `vpc_flow_logs` -- requires tenant to have enabled VPC Flow Logs on at
/// least one subnet. Zero records is the normal state on a fresh test project
/// (no compute, no flows).
#[tokio::test]
#[ignore = "requires live GCP credentials AND VPC Flow Logs enabled on a subnet"]
async fn gcp_fetch_vpc_flow_logs() {
    load_env();
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: "vpc_flow_logs".to_string(),
        config: HashMap::new(),
    });
    let source = GcpSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("vpc_flow_logs fetch failed");
    for r in &results {
        assert_eq!(r.source, "gcp.vpc_flow_logs");
    }
    eprintln!(
        "GCP vpc_flow_logs: {} record(s) (zero may indicate tenant has not \
         enabled VPC Flow Logs)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// `dns_queries` -- requires tenant to have a DNS server policy with logging
/// enabled attached to a relevant network.
#[tokio::test]
#[ignore = "requires live GCP credentials AND Cloud DNS query logging enabled"]
async fn gcp_fetch_dns_queries() {
    load_env();
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: "dns_queries".to_string(),
        config: HashMap::new(),
    });
    let source = GcpSource::new(cfg);
    let results = source.fetch(None).await.expect("dns_queries fetch failed");
    for r in &results {
        assert_eq!(r.source, "gcp.dns_queries");
    }
    eprintln!(
        "GCP dns_queries: {} record(s) (zero may indicate tenant has not \
         enabled Cloud DNS query logging)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// `storage_access` -- gcs_bucket subset of Data Access audit logs. Same
/// tenant-side enablement as `data_access`. Zero records is the normal state
/// on a project with no GCS objects being read.
#[tokio::test]
#[ignore = "requires live GCP credentials AND Data Access audit enabled on tenant"]
async fn gcp_fetch_storage_access() {
    load_env();
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: "storage_access".to_string(),
        config: HashMap::new(),
    });
    let source = GcpSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("storage_access fetch failed");
    for r in &results {
        assert_eq!(r.source, "gcp.storage_access");
    }
    eprintln!(
        "GCP storage_access: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// M365 -- OAuth2 against Office Mgmt API + Graph
//
// Reuses Azure credentials: the dfe-fetcher-azure-test SP in the HyperI MS
// tenant has both Azure Management and Graph permissions granted.
// =============================================================================

fn m365_base() -> M365SourceConfig {
    M365SourceConfig {
        enabled: true,
        tenant_id: Some(require("AZURE_TENANT_ID")),
        client_id: Some(require("AZURE_CLIENT_ID")),
        client_secret: Some(require("AZURE_CLIENT_SECRET").into()),
        credential_secret: None,
        interval_secs: None,
        services: vec![],
        topic: "test-m365".to_string(),
        filter: None,
        management_url_override: None,
        graph_url_override: None,
        token_url_override: None,
    }
}

#[tokio::test]
#[ignore = "requires live M365 credentials (reuses Azure SP)"]
async fn m365_health_check() {
    load_env();
    let cfg = m365_base();
    let source = M365Source::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("M365 health_check errored");
    assert!(healthy, "M365 health check failed with valid credentials");
}

/// `audit_log` with default content_types -- exercises all five OMAP feeds:
/// Audit.General, Audit.AzureActiveDirectory, Audit.Exchange, Audit.SharePoint,
/// DLP.All. Each feed surfaces as its own FetchResult tagged
/// `m365.audit_log.<content_type>`.
#[tokio::test]
#[ignore = "requires live M365 credentials"]
async fn m365_fetch_audit_log_all_content_types() {
    load_env();
    let mut cfg = m365_base();
    cfg.services.push(M365Service {
        name: "audit_log".to_string(),
        config: HashMap::new(),
    });
    let source = M365Source::new(cfg);
    let results = source.fetch(None).await.expect("audit_log fetch failed");

    eprintln!(
        "M365 audit_log: {} result(s) across content types",
        results.len()
    );
    for r in &results {
        eprintln!("  {}: {} record(s)", r.source, r.records.len());
        assert!(
            r.source.starts_with("m365.audit_log."),
            "audit_log result source should be tagged with content type, got {}",
            r.source
        );
    }
}

/// Single-content-type opt-in: only fetch Audit.SharePoint. Verifies the
/// `content_types` service-config override works and only one FetchResult
/// comes back.
#[tokio::test]
#[ignore = "requires live M365 credentials"]
async fn m365_fetch_audit_log_sharepoint_only() {
    load_env();
    let mut svc_config = HashMap::new();
    svc_config.insert(
        "content_types".into(),
        serde_json::json!(["Audit.SharePoint"]),
    );

    let mut cfg = m365_base();
    cfg.services.push(M365Service {
        name: "audit_log".to_string(),
        config: svc_config,
    });
    let source = M365Source::new(cfg);
    let results = source.fetch(None).await.expect("audit_log fetch failed");

    // Zero or one result depending on whether SharePoint had activity in the
    // last lookback window. Crucially: no other content types should appear.
    for r in &results {
        assert_eq!(
            r.source, "m365.audit_log.audit_sharepoint",
            "unexpected content type in single-opt-in fetch: {}",
            r.source
        );
    }
    eprintln!(
        "M365 audit_log[SharePoint]: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// `dlp` switched from Graph alerts_v2 to OMAP DLP.All in 2026-05-21 refactor.
/// Verifies raw DLP rule-match events come back (not post-classified alerts).
#[tokio::test]
#[ignore = "requires live M365 credentials"]
async fn m365_fetch_dlp_via_omap() {
    load_env();
    let mut cfg = m365_base();
    cfg.services.push(M365Service {
        name: "dlp".to_string(),
        config: HashMap::new(),
    });
    let source = M365Source::new(cfg);
    let results = source.fetch(None).await.expect("dlp fetch failed");

    for r in &results {
        assert_eq!(r.source, "m365.dlp", "dlp result should be tagged m365.dlp");
    }
    eprintln!(
        "M365 dlp: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// `alerts` via Microsoft Graph alerts_v2. Requires `SecurityAlert.Read.All`
/// app permission to be granted to the SP -- if it isn't, this test fails
/// loudly with the Graph 403, which is the desired signal (rather than
/// silently passing while alerts are broken).
#[tokio::test]
#[ignore = "requires live M365 credentials AND SecurityAlert.Read.All grant"]
async fn m365_fetch_alerts_via_graph() {
    load_env();
    let mut cfg = m365_base();
    cfg.services.push(M365Service {
        name: "alerts".to_string(),
        config: HashMap::new(),
    });
    let source = M365Source::new(cfg);
    let results = source.fetch(None).await.expect("alerts fetch failed");

    for r in &results {
        assert_eq!(r.source, "m365.alerts");
    }
    eprintln!(
        "M365 alerts: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// GitHub audit log -- bearer-token PAT or GitHub App against api.github.com
// =============================================================================

fn github_base() -> GithubSourceConfig {
    let token = require("GITHUB_AUDIT_TOKEN");
    let org = optional("GITHUB_AUDIT_ORG");
    let enterprise = optional("GITHUB_AUDIT_ENTERPRISE");
    assert!(
        org.is_some() || enterprise.is_some(),
        "set exactly one of GITHUB_AUDIT_ORG or GITHUB_AUDIT_ENTERPRISE in .env-cloud"
    );
    GithubSourceConfig {
        enabled: true,
        org,
        enterprise,
        token: Some(token.into()),
        credential_secret: None,
        api_url_override: None,
        interval_secs: None,
        services: vec![],
        topic: "test-github".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live GitHub credentials"]
async fn github_health_check() {
    load_env();
    let mut cfg = github_base();
    cfg.services.push(GithubService {
        name: "audit_log".to_string(),
        config: HashMap::new(),
    });
    let source = GithubSource::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("GitHub health_check errored");
    assert!(healthy, "GitHub health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live GitHub credentials"]
async fn github_fetch_audit_log() {
    load_env();
    let mut cfg = github_base();
    cfg.services.push(GithubService {
        name: "audit_log".to_string(),
        config: HashMap::new(),
    });
    let source = GithubSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("GitHub audit_log fetch failed");
    for r in &results {
        assert_eq!(r.source, "github.audit_log");
    }
    eprintln!(
        "GitHub audit_log: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

#[tokio::test]
#[ignore = "requires live GitHub credentials"]
async fn github_fetch_audit_log_git_events_only() {
    load_env();
    let mut svc_config = HashMap::new();
    svc_config.insert("include".into(), serde_json::Value::String("git".into()));
    let mut cfg = github_base();
    cfg.services.push(GithubService {
        name: "audit_log".to_string(),
        config: svc_config,
    });
    let source = GithubSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("GitHub audit_log[git] fetch failed");
    for r in &results {
        assert_eq!(r.source, "github.audit_log");
    }
    eprintln!(
        "GitHub audit_log[git]: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// Okta -- SSWS API token against /api/v1/logs
// =============================================================================

fn okta_base() -> OktaSourceConfig {
    OktaSourceConfig {
        enabled: true,
        tenant_url: Some(require("OKTA_TENANT_URL")),
        token: Some(require("OKTA_TOKEN").into()),
        use_ssws_header: optional("OKTA_USE_SSWS")
            .map(|v| matches!(v.as_str(), "1" | "true" | "TRUE" | "yes"))
            .unwrap_or(true),
        credential_secret: None,
        api_url_override: None,
        interval_secs: None,
        services: vec![],
        topic: "test-okta".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live Okta credentials"]
async fn okta_health_check() {
    load_env();
    let mut cfg = okta_base();
    cfg.services.push(OktaService {
        name: "system_log".to_string(),
        config: HashMap::new(),
    });
    let source = OktaSource::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("Okta health_check errored");
    assert!(healthy, "Okta health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live Okta credentials"]
async fn okta_fetch_system_log() {
    load_env();
    let mut cfg = okta_base();
    cfg.services.push(OktaService {
        name: "system_log".to_string(),
        config: HashMap::new(),
    });
    let source = OktaSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("Okta system_log fetch failed");
    for r in &results {
        assert_eq!(r.source, "okta.system_log");
    }
    eprintln!(
        "Okta system_log: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

/// `system_log` with an OData filter applied server-side.
#[tokio::test]
#[ignore = "requires live Okta credentials"]
async fn okta_fetch_system_log_with_filter() {
    load_env();
    let mut svc_config = HashMap::new();
    svc_config.insert(
        "filter".into(),
        serde_json::Value::String(r#"eventType eq "user.session.start""#.into()),
    );
    let mut cfg = okta_base();
    cfg.services.push(OktaService {
        name: "system_log".to_string(),
        config: svc_config,
    });
    let source = OktaSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("Okta system_log[filter] fetch failed");
    for r in &results {
        assert_eq!(r.source, "okta.system_log");
    }
    eprintln!(
        "Okta system_log[filter]: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// Cloudflare -- bearer-token API against api.cloudflare.com
// =============================================================================

fn cloudflare_base() -> CloudflareSourceConfig {
    CloudflareSourceConfig {
        enabled: true,
        account_id: Some(require("CLOUDFLARE_ACCOUNT_ID")),
        token: Some(require("CLOUDFLARE_TOKEN").into()),
        credential_secret: None,
        api_url_override: None,
        interval_secs: None,
        services: vec![],
        topic: "test-cloudflare".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live Cloudflare credentials"]
async fn cloudflare_health_check() {
    load_env();
    let mut cfg = cloudflare_base();
    cfg.services.push(CloudflareService {
        name: "audit_logs".to_string(),
        config: HashMap::new(),
    });
    let source = CloudflareSource::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("Cloudflare health_check errored");
    assert!(
        healthy,
        "Cloudflare health check failed with valid credentials"
    );
}

#[tokio::test]
#[ignore = "requires live Cloudflare credentials"]
async fn cloudflare_fetch_audit_logs() {
    load_env();
    let mut cfg = cloudflare_base();
    cfg.services.push(CloudflareService {
        name: "audit_logs".to_string(),
        config: HashMap::new(),
    });
    let source = CloudflareSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("Cloudflare audit_logs fetch failed");
    for r in &results {
        assert_eq!(r.source, "cloudflare.audit_logs");
    }
    eprintln!(
        "Cloudflare audit_logs: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// 1Password Events Reporting -- bearer token against events.1password.com
// =============================================================================

fn onepassword_base() -> OnePasswordSourceConfig {
    OnePasswordSourceConfig {
        enabled: true,
        token: Some(require("ONEPASSWORD_EVENTS_TOKEN").into()),
        credential_secret: None,
        api_url_override: optional("ONEPASSWORD_API_BASE"),
        interval_secs: None,
        services: vec![],
        topic: "test-onepassword".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live 1Password Business credentials"]
async fn onepassword_health_check() {
    load_env();
    let mut cfg = onepassword_base();
    cfg.services.push(OnePasswordService {
        name: "audit_events".to_string(),
        config: HashMap::new(),
    });
    let source = OnePasswordSource::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("1Password health_check errored");
    assert!(
        healthy,
        "1Password health check failed with valid credentials"
    );
}

#[tokio::test]
#[ignore = "requires live 1Password Business credentials"]
async fn onepassword_fetch_signin_attempts() {
    load_env();
    let mut cfg = onepassword_base();
    cfg.services.push(OnePasswordService {
        name: "signin_attempts".to_string(),
        config: HashMap::new(),
    });
    let source = OnePasswordSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("1Password signin_attempts fetch failed");
    for r in &results {
        assert_eq!(r.source, "onepassword.signin_attempts");
    }
    eprintln!(
        "1Password signin_attempts: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

#[tokio::test]
#[ignore = "requires live 1Password Business credentials"]
async fn onepassword_fetch_item_usages() {
    load_env();
    let mut cfg = onepassword_base();
    cfg.services.push(OnePasswordService {
        name: "item_usages".to_string(),
        config: HashMap::new(),
    });
    let source = OnePasswordSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("1Password item_usages fetch failed");
    for r in &results {
        assert_eq!(r.source, "onepassword.item_usages");
    }
    eprintln!(
        "1Password item_usages: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

#[tokio::test]
#[ignore = "requires live 1Password Business credentials"]
async fn onepassword_fetch_audit_events() {
    load_env();
    let mut cfg = onepassword_base();
    cfg.services.push(OnePasswordService {
        name: "audit_events".to_string(),
        config: HashMap::new(),
    });
    let source = OnePasswordSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("1Password audit_events fetch failed");
    for r in &results {
        assert_eq!(r.source, "onepassword.audit_events");
    }
    eprintln!(
        "1Password audit_events: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// CrowdStrike Falcon -- OAuth2 client_credentials against api.crowdstrike.com
// =============================================================================

fn crowdstrike_base() -> CrowdstrikeSourceConfig {
    CrowdstrikeSourceConfig {
        enabled: true,
        api_url_override: optional("CROWDSTRIKE_API_BASE"),
        client_id: Some(require("CROWDSTRIKE_CLIENT_ID")),
        client_secret: Some(require("CROWDSTRIKE_CLIENT_SECRET").into()),
        credential_secret: None,
        interval_secs: None,
        services: vec![],
        topic: "test-crowdstrike".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live CrowdStrike Falcon credentials"]
async fn crowdstrike_health_check() {
    load_env();
    let mut cfg = crowdstrike_base();
    cfg.services.push(CrowdstrikeService {
        name: "alerts".to_string(),
        config: HashMap::new(),
    });
    let source = CrowdstrikeSource::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("CrowdStrike health_check errored");
    assert!(
        healthy,
        "CrowdStrike health check failed with valid credentials"
    );
}

#[tokio::test]
#[ignore = "requires live CrowdStrike Falcon credentials"]
async fn crowdstrike_fetch_alerts() {
    load_env();
    let mut cfg = crowdstrike_base();
    cfg.services.push(CrowdstrikeService {
        name: "alerts".to_string(),
        config: HashMap::new(),
    });
    let source = CrowdstrikeSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("CrowdStrike alerts fetch failed");
    for r in &results {
        assert_eq!(r.source, "crowdstrike.alerts");
    }
    eprintln!(
        "CrowdStrike alerts: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// Slack -- bearer-token against api.slack.com/audit/v1/logs
// =============================================================================

fn slack_base() -> SlackSourceConfig {
    SlackSourceConfig {
        enabled: true,
        token: Some(require("SLACK_AUDIT_TOKEN").into()),
        credential_secret: None,
        api_url_override: None,
        interval_secs: None,
        services: vec![],
        topic: "test-slack".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live Slack Enterprise Grid credentials"]
async fn slack_health_check() {
    load_env();
    let mut cfg = slack_base();
    cfg.services.push(SlackService {
        name: "audit_logs".to_string(),
        config: HashMap::new(),
    });
    let source = SlackSource::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("Slack health_check errored");
    assert!(healthy, "Slack health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live Slack Enterprise Grid credentials"]
async fn slack_fetch_audit_logs() {
    load_env();
    let mut cfg = slack_base();
    cfg.services.push(SlackService {
        name: "audit_logs".to_string(),
        config: HashMap::new(),
    });
    let source = SlackSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("Slack audit_logs fetch failed");
    for r in &results {
        assert_eq!(r.source, "slack.audit_logs");
    }
    eprintln!(
        "Slack audit_logs: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// Bitwarden -- OAuth2 client_credentials against api.bitwarden.com
// =============================================================================

fn bitwarden_base() -> BitwardenSourceConfig {
    BitwardenSourceConfig {
        enabled: true,
        client_id: Some(require("BITWARDEN_CLIENT_ID")),
        client_secret: Some(require("BITWARDEN_CLIENT_SECRET").into()),
        credential_secret: None,
        api_url_override: optional("BITWARDEN_API_BASE"),
        identity_url_override: optional("BITWARDEN_IDENTITY_URL"),
        interval_secs: None,
        services: vec![],
        topic: "test-bitwarden".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live Bitwarden organisation credentials"]
async fn bitwarden_health_check() {
    load_env();
    let mut cfg = bitwarden_base();
    cfg.services.push(BitwardenService {
        name: "events".to_string(),
        config: HashMap::new(),
    });
    let source = BitwardenSource::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("Bitwarden health_check errored");
    assert!(
        healthy,
        "Bitwarden health check failed with valid credentials"
    );
}

#[tokio::test]
#[ignore = "requires live Bitwarden organisation credentials"]
async fn bitwarden_fetch_events() {
    load_env();
    let mut cfg = bitwarden_base();
    cfg.services.push(BitwardenService {
        name: "events".to_string(),
        config: HashMap::new(),
    });
    let source = BitwardenSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("Bitwarden events fetch failed");
    for r in &results {
        assert_eq!(r.source, "bitwarden.events");
    }
    eprintln!(
        "Bitwarden events: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// Duo -- HMAC-SHA1 signed requests to api-XXXXXXXX.duosecurity.com
// =============================================================================

fn duo_base() -> DuoSourceConfig {
    DuoSourceConfig {
        enabled: true,
        api_host: Some(require("DUO_API_HOST")),
        integration_key: Some(require("DUO_INTEGRATION_KEY")),
        secret_key: Some(require("DUO_SECRET_KEY").into()),
        credential_secret: None,
        api_url_override: None,
        interval_secs: None,
        services: vec![],
        topic: "test-duo".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live Duo Admin API credentials"]
async fn duo_health_check() {
    load_env();
    let mut cfg = duo_base();
    cfg.services.push(DuoService {
        name: "authentication_logs".to_string(),
        config: HashMap::new(),
    });
    let source = DuoSource::new(cfg);
    let healthy = source
        .health_check()
        .await
        .expect("Duo health_check errored");
    assert!(healthy, "Duo health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live Duo Admin API credentials"]
async fn duo_fetch_authentication_logs() {
    load_env();
    let mut cfg = duo_base();
    cfg.services.push(DuoService {
        name: "authentication_logs".to_string(),
        config: HashMap::new(),
    });
    let source = DuoSource::new(cfg);
    let results = source
        .fetch(None)
        .await
        .expect("Duo authentication_logs fetch failed");
    for r in &results {
        assert_eq!(r.source, "duo.authentication_logs");
    }
    eprintln!(
        "Duo authentication_logs: {} record(s)",
        results.iter().map(|r| r.records.len()).sum::<usize>()
    );
}

// =============================================================================
// Public-registry supply-chain audit -- no auth, hits public APIs.
// `#[ignore]` because they reach external services on every run.
// =============================================================================

#[tokio::test]
#[ignore = "hits public PyPI - keep out of fast test runs"]
async fn pypi_fetch_known_packages() {
    load_env();
    let mut cfg = PypiSourceConfig {
        enabled: true,
        // `pip` and `setuptools` are stable, always-present packages.
        packages: vec!["pip".to_string(), "setuptools".to_string()],
        ..PypiSourceConfig::default()
    };
    cfg.topic = "test-pypi".to_string();
    let source = PypiSource::new(cfg);
    let results = source.fetch(None).await.expect("PyPI fetch failed");
    assert_eq!(
        results.len(),
        1,
        "PyPI emits one result containing all packages"
    );
    let r = &results[0];
    assert_eq!(r.source, "pypi.metadata");
    assert_eq!(
        r.records.len(),
        2,
        "expected one record per configured package"
    );
    eprintln!("PyPI: {} record(s)", r.records.len());
}

#[tokio::test]
#[ignore = "hits public crates.io - keep out of fast test runs"]
async fn crates_io_fetch_known_crates() {
    load_env();
    let mut cfg = CratesIoSourceConfig {
        enabled: true,
        // `serde` and `tokio` are stable, always-present crates.
        crates: vec!["serde".to_string(), "tokio".to_string()],
        ..CratesIoSourceConfig::default()
    };
    cfg.topic = "test-crates_io".to_string();
    let source = CratesIoSource::new(cfg);
    let results = source.fetch(None).await.expect("crates.io fetch failed");
    assert_eq!(results.len(), 1);
    let r = &results[0];
    assert_eq!(r.source, "crates_io.metadata");
    assert_eq!(r.records.len(), 2);
    eprintln!("crates.io: {} record(s)", r.records.len());
}

#[tokio::test]
#[ignore = "hits public Go proxy - keep out of fast test runs"]
async fn go_modules_fetch_known_module() {
    load_env();
    let mut cfg = GoModulesSourceConfig {
        enabled: true,
        // `golang.org/x/text` is a stable, always-present Go module.
        modules: vec!["golang.org/x/text".to_string()],
        ..GoModulesSourceConfig::default()
    };
    cfg.topic = "test-go_modules".to_string();
    let source = GoModulesSource::new(cfg);
    let results = source.fetch(None).await.expect("Go proxy fetch failed");
    assert_eq!(results.len(), 1);
    let r = &results[0];
    assert_eq!(r.source, "go_modules.metadata");
    assert_eq!(r.records.len(), 1);
    eprintln!("Go modules: {} record(s)", r.records.len());
}

// =============================================================================
// Google Workspace Reports API -- SPECULATIVE
// =============================================================================
//
// These tests will fail on every supported environment until
// hyperi-infra#5 is completed:
//   1. A GCP service account with domain-wide delegation provisioned.
//   2. Reports API scope manually granted in the Admin console
//      (Security -> API controls -> Domain-wide delegation).
//   3. Admin email surfaced in env so the JWT `sub` claim impersonates it.
//
// The fetcher code is written and unit-tested; the live tests stay
// `#[ignore]`'d and additionally noted as pending the infra issue.

fn google_workspace_base() -> GoogleWorkspaceSourceConfig {
    GoogleWorkspaceSourceConfig {
        enabled: true,
        service_account_key: optional("GOOGLE_WORKSPACE_SA_KEY"),
        credential_secret: optional("GOOGLE_WORKSPACE_CREDENTIAL_SECRET"),
        admin_email: optional("GOOGLE_WORKSPACE_ADMIN_EMAIL"),
        customer_id: optional("GOOGLE_WORKSPACE_CUSTOMER_ID"),
        api_url_override: optional("GOOGLE_WORKSPACE_API_URL"),
        token_url_override: optional("GOOGLE_WORKSPACE_TOKEN_URL"),
        topic: "test-google_workspace".to_string(),
        ..GoogleWorkspaceSourceConfig::default()
    }
}

#[tokio::test]
#[ignore = "requires Workspace SA + admin scope grant (hyperi-infra#5 must be completed first)"]
async fn google_workspace_health_check() {
    load_env();
    let _ = require("GOOGLE_WORKSPACE_ADMIN_EMAIL");
    // SA may be supplied via key file OR vault spec; at least one is required
    if optional("GOOGLE_WORKSPACE_SA_KEY").is_none()
        && optional("GOOGLE_WORKSPACE_CREDENTIAL_SECRET").is_none()
    {
        panic!("missing GOOGLE_WORKSPACE_SA_KEY or GOOGLE_WORKSPACE_CREDENTIAL_SECRET");
    }
    let src = GoogleWorkspaceSource::new(google_workspace_base());
    let ok = src
        .health_check()
        .await
        .expect("Workspace health_check errored");
    assert!(ok, "Workspace health_check returned false");
}

#[tokio::test]
#[ignore = "requires Workspace SA + admin scope grant (hyperi-infra#5 must be completed first)"]
async fn google_workspace_login_activity_fetch() {
    load_env();
    let _ = require("GOOGLE_WORKSPACE_ADMIN_EMAIL");
    if optional("GOOGLE_WORKSPACE_SA_KEY").is_none()
        && optional("GOOGLE_WORKSPACE_CREDENTIAL_SECRET").is_none()
    {
        panic!("missing GOOGLE_WORKSPACE_SA_KEY or GOOGLE_WORKSPACE_CREDENTIAL_SECRET");
    }
    let mut cfg = google_workspace_base();
    cfg.services = vec![GoogleWorkspaceService {
        name: "login".to_string(),
        config: HashMap::default(),
    }];
    let src = GoogleWorkspaceSource::new(cfg);
    let results = src.fetch(None).await.expect("Workspace fetch failed");
    // Real tenants typically have at least one login event in the last
    // hour, but we don't assert presence - an empty window is valid.
    let total: usize = results.iter().map(|r| r.records.len()).sum();
    eprintln!(
        "Workspace login: {} FetchResult(s), {} record(s) total",
        results.len(),
        total
    );
    for r in &results {
        assert!(
            r.source.starts_with("google_workspace."),
            "unexpected source tag: {}",
            r.source
        );
    }
}

// =============================================================================
// GCP Pub/Sub pull -- SPECULATIVE
// =============================================================================
//
// These tests will fail on every supported environment until the
// pending hyperi-infra issue is completed:
//   1. A Cloud Logging Log Sink routing entries into a Pub/Sub topic.
//   2. A Pub/Sub subscription on that topic.
//   3. `roles/pubsub.subscriber` granted to the fetcher SA on that
//      subscription.
//
// The fetcher code is written and unit-tested; the live tests stay
// `#[ignore]`'d and additionally noted as pending the infra issue.

fn gcp_pubsub_base() -> GcpPubsubSourceConfig {
    GcpPubsubSourceConfig {
        enabled: true,
        service_account_key: optional("GCP_PUBSUB_SA_KEY"),
        credential_secret: optional("GCP_PUBSUB_CREDENTIAL_SECRET"),
        api_url_override: optional("GCP_PUBSUB_API_URL"),
        token_url_override: optional("GCP_PUBSUB_TOKEN_URL"),
        topic: "test-gcp_pubsub".to_string(),
        ..GcpPubsubSourceConfig::default()
    }
}

#[tokio::test]
#[ignore = "requires Pub/Sub Log Sink + subscription (pending hyperi-infra issue TBD)"]
async fn gcp_pubsub_health_check() {
    load_env();
    assert!(
        optional("GCP_PUBSUB_SA_KEY").is_some()
            || optional("GCP_PUBSUB_CREDENTIAL_SECRET").is_some(),
        "missing GCP_PUBSUB_SA_KEY or GCP_PUBSUB_CREDENTIAL_SECRET"
    );
    let src = GcpPubsubSource::new(gcp_pubsub_base());
    let ok = src
        .health_check()
        .await
        .expect("Pub/Sub health_check errored");
    assert!(ok, "Pub/Sub health_check returned false");
}

#[tokio::test]
#[ignore = "requires Pub/Sub Log Sink + subscription (pending hyperi-infra issue TBD)"]
async fn gcp_pubsub_pull_subscription() {
    load_env();
    assert!(
        optional("GCP_PUBSUB_SA_KEY").is_some()
            || optional("GCP_PUBSUB_CREDENTIAL_SECRET").is_some(),
        "missing GCP_PUBSUB_SA_KEY or GCP_PUBSUB_CREDENTIAL_SECRET"
    );
    let project = require("GCP_PUBSUB_PROJECT_ID");
    let sub_id = require("GCP_PUBSUB_SUBSCRIPTION_ID");
    let mut cfg = gcp_pubsub_base();
    cfg.subscriptions = vec![GcpPubsubSubscription {
        project_id: project,
        subscription_id: sub_id,
        max_messages: 10,
        return_immediately: true,
    }];
    let src = GcpPubsubSource::new(cfg);
    let results = src.fetch(None).await.expect("Pub/Sub fetch failed");
    let total: usize = results.iter().map(|r| r.records.len()).sum();
    eprintln!(
        "Pub/Sub: {} FetchResult(s), {} record(s) total",
        results.len(),
        total
    );
    for r in &results {
        assert!(
            r.source.starts_with("gcp_pubsub."),
            "unexpected source tag: {}",
            r.source
        );
    }
}

// =============================================================================
// Object-store source family -- S3 backend live; GCS/Azure Blob Phase 2 stubs
// =============================================================================
//
// S3 tests use the existing AWS test credentials (.env-cloud AWS_*). To
// target a specific test bucket, set OBJECT_STORE_S3_BUCKET +
// OBJECT_STORE_S3_PREFIX (defaults pick the existing ESH_S3_BUCKET with
// an empty prefix).

fn object_store_s3_config() -> S3BackendConfig {
    S3BackendConfig {
        region: optional("OBJECT_STORE_S3_REGION")
            .or_else(|| optional("AWS_REGION"))
            .unwrap_or_else(|| "us-west-2".into()),
        endpoint_override: optional("OBJECT_STORE_S3_ENDPOINT"),
        access_key_id: Some(require("AWS_ACCESS_KEY_ID")),
        secret_access_key: Some(require("AWS_SECRET_ACCESS_KEY").into()),
        credential_secret: None,
        buckets: vec![],
    }
}

#[tokio::test]
#[ignore = "requires live AWS credentials + an S3 bucket the fetcher SA can list"]
async fn object_store_s3_list_only() {
    load_env();
    let bucket = optional("OBJECT_STORE_S3_BUCKET")
        .or_else(|| optional("ESH_S3_BUCKET"))
        .expect("set OBJECT_STORE_S3_BUCKET or ESH_S3_BUCKET in .env-cloud");
    let prefix = optional("OBJECT_STORE_S3_PREFIX").unwrap_or_default();

    let mut s3 = object_store_s3_config();
    s3.buckets = vec![ObjectStoreBucket {
        bucket: bucket.clone(),
        prefixes: vec![ObjectStorePrefix {
            prefix: prefix.clone(),
            format: ObjectStoreFormat::Jsonl,
            source_tag: "smoke_test".to_string(),
            topic: None,
        }],
    }];

    let cfg = ObjectStoreSourceConfig {
        enabled: true,
        backends: vec![ObjectStoreBackendConfig::S3(s3)],
        interval_secs: None,
        topic: "test-object_store".to_string(),
        filter: None,
    };
    let src = ObjectStoreSource::new(cfg);
    // Empty bucket -> Ok(vec![]) is a valid outcome. We just want to
    // assert the list call signs + executes without error.
    let results = src.fetch(None).await.expect("object_store fetch errored");
    let total: usize = results.iter().map(|r| r.records.len()).sum();
    eprintln!(
        "object_store s3({bucket}/{prefix}): {} FetchResult(s), {total} record(s) total",
        results.len(),
    );
}

#[tokio::test]
#[ignore = "requires AWS credentials AND an S3 prefix with at least one gzipped JSON-lines object"]
async fn object_store_s3_parse_json_gz_objects() {
    load_env();
    let bucket = require("OBJECT_STORE_S3_BUCKET");
    let prefix = require("OBJECT_STORE_S3_PREFIX");

    let mut s3 = object_store_s3_config();
    s3.buckets = vec![ObjectStoreBucket {
        bucket: bucket.clone(),
        prefixes: vec![ObjectStorePrefix {
            prefix: prefix.clone(),
            format: ObjectStoreFormat::JsonGz,
            source_tag: "smoke_test_json_gz".to_string(),
            topic: None,
        }],
    }];
    let cfg = ObjectStoreSourceConfig {
        enabled: true,
        backends: vec![ObjectStoreBackendConfig::S3(s3)],
        interval_secs: None,
        topic: "test-object_store".to_string(),
        filter: None,
    };
    let src = ObjectStoreSource::new(cfg);
    let results = src.fetch(None).await.expect("object_store fetch errored");
    let total: usize = results.iter().map(|r| r.records.len()).sum();
    eprintln!(
        "object_store s3({bucket}/{prefix}) json_gz: {} FetchResult(s), {total} record(s) total",
        results.len(),
    );
    for r in &results {
        assert!(
            r.source.starts_with("object_store."),
            "unexpected source tag: {}",
            r.source
        );
        for rec in &r.records {
            let parsed: serde_json::Value =
                serde_json::from_slice(rec).expect("each emitted record must be valid JSON");
            // Every record carries the envelope; the bucket name is the
            // ground truth we asserted on.
            assert_eq!(parsed["_dfe_fetcher_object"]["bucket"], bucket.as_str());
        }
    }
}

// =============================================================================
// Salesforce -- SetupAuditTrail + LoginHistory (SOQL) + EventLogFile (CSV)
// =============================================================================
//
// Auth picks JWT bearer when SALESFORCE_PRIVATE_KEY[_PATH] is set, else
// client credentials via SALESFORCE_CLIENT_SECRET. Requires a connected app
// in the target org + an integration user with API Enabled, View Setup Audit
// Trail, and (for event_log_file) View Event Log Files.

fn salesforce_base() -> SalesforceSourceConfig {
    SalesforceSourceConfig {
        enabled: true,
        login_url: optional("SALESFORCE_LOGIN_URL"),
        api_version: optional("SALESFORCE_API_VERSION"),
        client_id: optional("SALESFORCE_CLIENT_ID"),
        username: optional("SALESFORCE_USERNAME"),
        private_key: optional("SALESFORCE_PRIVATE_KEY"),
        private_key_secret: optional("SALESFORCE_PRIVATE_KEY_SECRET"),
        client_secret: optional("SALESFORCE_CLIENT_SECRET").map(Into::into),
        credential_secret: optional("SALESFORCE_CREDENTIAL_SECRET"),
        instance_url_override: optional("SALESFORCE_INSTANCE_URL"),
        topic: "test-salesforce".to_string(),
        ..SalesforceSourceConfig::default()
    }
}

fn salesforce_has_auth() -> bool {
    optional("SALESFORCE_CLIENT_ID").is_some()
        && (optional("SALESFORCE_PRIVATE_KEY").is_some()
            || optional("SALESFORCE_PRIVATE_KEY_SECRET").is_some()
            || optional("SALESFORCE_CLIENT_SECRET").is_some()
            || optional("SALESFORCE_CREDENTIAL_SECRET").is_some())
}

#[tokio::test]
#[ignore = "requires a Salesforce connected app + integration user"]
async fn salesforce_health_check() {
    load_env();
    assert!(
        salesforce_has_auth(),
        "missing SALESFORCE_CLIENT_ID + one of SALESFORCE_PRIVATE_KEY / \
         SALESFORCE_PRIVATE_KEY_SECRET / SALESFORCE_CLIENT_SECRET / \
         SALESFORCE_CREDENTIAL_SECRET"
    );
    let src = SalesforceSource::new(salesforce_base());
    let ok = src
        .health_check()
        .await
        .expect("Salesforce health_check errored");
    assert!(ok, "Salesforce health_check returned false");
}

#[tokio::test]
#[ignore = "requires a Salesforce connected app + integration user"]
async fn salesforce_setup_audit_trail_and_login_history() {
    load_env();
    assert!(salesforce_has_auth(), "missing Salesforce auth env vars");
    let mut cfg = salesforce_base();
    cfg.services = vec![
        SalesforceService {
            name: "setup_audit_trail".to_string(),
            config: HashMap::new(),
        },
        SalesforceService {
            name: "login_history".to_string(),
            config: HashMap::new(),
        },
    ];
    let src = SalesforceSource::new(cfg);
    let results = src.fetch(None).await.expect("Salesforce fetch failed");
    let total: usize = results.iter().map(|r| r.records.len()).sum();
    eprintln!(
        "Salesforce SOQL: {} FetchResult(s), {total} record(s) total",
        results.len(),
    );
    for r in &results {
        assert!(
            r.source.starts_with("salesforce."),
            "unexpected source tag: {}",
            r.source
        );
    }
}

#[tokio::test]
#[ignore = "requires Salesforce Event Monitoring (or the 7 free EventLogFile types)"]
async fn salesforce_event_log_file() {
    load_env();
    assert!(salesforce_has_auth(), "missing Salesforce auth env vars");
    let mut cfg = salesforce_base();
    cfg.services = vec![SalesforceService {
        name: "event_log_file".to_string(),
        config: HashMap::new(),
    }];
    let src = SalesforceSource::new(cfg);
    let results = src.fetch(None).await.expect("Salesforce ELF fetch failed");
    let total: usize = results.iter().map(|r| r.records.len()).sum();
    eprintln!(
        "Salesforce EventLogFile: {} FetchResult(s), {total} record(s) total",
        results.len(),
    );
    for r in &results {
        assert_eq!(r.source, "salesforce.event_log_file");
        for rec in &r.records {
            let parsed: serde_json::Value =
                serde_json::from_slice(rec).expect("each ELF record must be valid JSON");
            assert!(
                parsed["_dfe_fetcher_event_type"].is_string(),
                "ELF record missing _dfe_fetcher_event_type envelope"
            );
        }
    }
}
