// Project:   dfe-fetcher
// File:      crates/fetcher/tests/e2e/smoke_remote.rs
// Purpose:   Live remote-source smoke tests (cloud APIs + SaaS audit logs)
// Language:  Rust
//
// License:   BUSL-1.1
// Copyright: (c) 2026 HYPERI PTY LIMITED

//! Live remote-source smoke tests against real tenants / SaaS accounts.
//!
//! Covers AWS, Azure, M365, GCP (cloud APIs) plus GitHub audit (SaaS). All
//! tests are `#[ignore]`d so they don't run on every push. To run them:
//!
//! ```bash
//! cargo nextest run --test e2e -- --ignored
//! # or filter to one source family:
//! cargo nextest run --test e2e -- --ignored github_
//! ```
//!
//! Credentials are loaded from `.env-cloud` (canonical, generated by
//! `infra/test/gen-env.py` from `kv/dfe-test/*`) with a fallback to `.env`.
//! Each test panics with a clear message if its required env vars are
//! missing -- no more silent skips that pretend to pass.
//!
//! ## Credential reuse
//!
//! The M365 tests read `M365_TENANT_ID`/`M365_CLIENT_ID`/`M365_CLIENT_SECRET`
//! and fall back to the `AZURE_*` trio: M365 IS Entra/Azure AD, and the
//! `dfe-fetcher-azure-test` SP in the HyperI MS tenant has both Azure
//! Management and Microsoft Graph permissions granted.
//!
//! ## Per-service isolation
//!
//! Each test exercises ONE service (`Source::fetch` aggregates across all
//! configured services and swallows errors, which previously masked broken
//! services as "passing"). Coverage is per-service so a regression in one
//! surface fails its own test.

use std::collections::HashMap;

use dfe_fetcher::config::{
    AwsService, AwsSourceConfig, AzureService, AzureSourceConfig, BitwardenService,
    BitwardenSourceConfig, CloudflareService, CloudflareSourceConfig, CratesIoSourceConfig,
    CrowdstrikeService, CrowdstrikeSourceConfig, DuoService, DuoSignatureVersion, DuoSourceConfig,
    GcpPubsubSourceConfig, GcpPubsubSubscription, GcpService, GcpSourceConfig, GithubService,
    GithubSourceConfig, GoModulesSourceConfig, GoogleWorkspaceService, GoogleWorkspaceSourceConfig,
    M365Service, M365SourceConfig, ObjectStoreBackendConfig, ObjectStoreBucket, ObjectStoreFormat,
    ObjectStorePrefix, ObjectStoreSourceConfig, OktaService, OktaSourceConfig, OnePasswordService,
    OnePasswordSourceConfig, PypiSourceConfig, S3BackendConfig, SalesforceService,
    SalesforceSourceConfig, SlackService, SlackSourceConfig,
};
use dfe_fetcher_core::RowSource;

// Env loading (.env-cloud canonical, .env fallback) lives in `common`, shared
// with the other live-credential modules of this binary.
use crate::common::{builtin_shape, load_env, optional, require, shape_rows};

// =============================================================================
// AWS -- SigV4 against real CloudTrail / CloudWatch, through the shipped
// `aws` profile the typed `sources.aws` block maps onto. Each unit is
// fetched off the shape as the driver would, so a refusal fails its own
// test instead of being swallowed.
// =============================================================================

fn aws_base() -> AwsSourceConfig {
    AwsSourceConfig {
        enabled: true,
        region: optional("AWS_REGION").unwrap_or_else(|| "ap-southeast-2".to_string()),
        access_key_id: Some(require("AWS_ACCESS_KEY_ID")),
        secret_access_key: Some(require("AWS_SECRET_ACCESS_KEY").into()),
        assume_role_arn: None,
        credential_secret: None,
        endpoint_override: None,
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-aws".to_string(),
        filter: None,
    }
}

/// One unit of the aws block as the profile fetches it, with the record
/// count printed.
async fn aws_fetch(
    unit: &str,
    config: HashMap<String, serde_json::Value>,
) -> Vec<serde_json::Value> {
    load_env();
    let mut cfg = aws_base();
    cfg.services.push(AwsService {
        name: unit.to_string(),
        config,
    });
    let shape = builtin_shape(cfg.instances().expect("aws block maps"));
    assert_eq!(
        format!("{}.{unit}", shape.connection_id()),
        format!("aws.{unit}")
    );
    let rows = shape_rows(&shape, unit)
        .await
        .unwrap_or_else(|e| panic!("AWS {unit} fetch failed: {e}"));
    eprintln!("AWS {unit}: {} record(s)", rows.len());
    rows
}

/// The STS `GetCallerIdentity` probe with the configured key.
#[tokio::test]
#[ignore = "requires live AWS credentials"]
async fn aws_health_check() {
    load_env();
    let mut cfg = aws_base();
    cfg.services.push(AwsService {
        name: "cloudtrail".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("aws block maps"));
    shape
        .probe()
        .await
        .expect("AWS health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live AWS credentials"]
async fn aws_fetch_cloudtrail() {
    aws_fetch("cloudtrail", HashMap::new()).await;
}

#[tokio::test]
#[ignore = "requires live AWS credentials"]
async fn aws_fetch_cloudwatch_logs() {
    load_env();
    let log_group = optional("AWS_CLOUDWATCH_LOG_GROUP").unwrap_or_else(|| "vpc_flow_logs".into());
    let mut svc_config = HashMap::new();
    svc_config.insert(
        "log_group_name".into(),
        serde_json::Value::String(log_group),
    );
    aws_fetch("cloudwatch_logs", svc_config).await;
}

#[tokio::test]
#[ignore = "requires live AWS credentials"]
async fn aws_fetch_cloudwatch_metrics() {
    let mut svc_config = HashMap::new();
    svc_config.insert("namespaces".into(), serde_json::json!(["AWS/EC2"]));
    aws_fetch("cloudwatch_metrics", svc_config).await;
}

/// `inspector` -- requires tenant to have Inspector v2 enabled. Zero records
/// is the normal state on a test account with no scan-able resources.
#[tokio::test]
#[ignore = "requires live AWS credentials AND Inspector v2 enabled on tenant"]
async fn aws_fetch_inspector() {
    aws_fetch("inspector", HashMap::new()).await;
}

/// `health` -- requires Business / Enterprise On-Ramp / Enterprise support
/// tier on the AWS account; lesser tiers answer SubscriptionRequiredException,
/// which fails the test as it should.
#[tokio::test]
#[ignore = "requires live AWS credentials AND Business+ support tier"]
async fn aws_fetch_health() {
    aws_fetch("health", HashMap::new()).await;
}

/// `guardduty` -- every finding of every detector in the region.
#[tokio::test]
#[ignore = "requires live AWS credentials"]
async fn aws_fetch_guardduty() {
    aws_fetch("guardduty", HashMap::new()).await;
}

/// `securityhub` -- every finding in the region updated in the window, in any
/// workflow status.
#[tokio::test]
#[ignore = "requires live AWS credentials AND Security Hub enabled"]
async fn aws_fetch_securityhub() {
    aws_fetch("securityhub", HashMap::new()).await;
}

/// `config` -- every recorded resource's configuration; the key needs
/// `config:SelectResourceConfig`.
#[tokio::test]
#[ignore = "requires live AWS credentials AND config:SelectResourceConfig"]
async fn aws_fetch_config() {
    aws_fetch("config", HashMap::new()).await;
}

// =============================================================================
// Azure -- OAuth2 client_credentials against real Activity Log / Sentinel,
// through the shipped `azure` profile the typed `sources.azure` block maps
// onto. Each unit is fetched off the shape as the driver would, so a refusal
// fails its own test instead of being swallowed.
// =============================================================================

fn azure_base() -> AzureSourceConfig {
    AzureSourceConfig {
        enabled: true,
        tenant_id: Some(require("AZURE_TENANT_ID")),
        client_id: Some(require("AZURE_CLIENT_ID")),
        client_secret: Some(require("AZURE_CLIENT_SECRET").into()),
        credential_secret: None,
        subscription_id: Some(require("AZURE_SUBSCRIPTION_ID")),
        management_url_override: None,
        graph_url_override: None,
        token_url_override: None,
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-azure".to_string(),
        filter: None,
    }
}

/// One unit of the azure block as the profile fetches it, with the record
/// count printed.
async fn azure_fetch(
    unit: &str,
    config: HashMap<String, serde_json::Value>,
) -> Vec<serde_json::Value> {
    load_env();
    let mut cfg = azure_base();
    cfg.services.push(AzureService {
        name: unit.to_string(),
        config,
    });
    let shape = builtin_shape(cfg.instances().expect("azure block maps"));
    assert_eq!(
        format!("{}.{unit}", shape.connection_id()),
        format!("azure.{unit}")
    );
    let rows = shape_rows(&shape, unit)
        .await
        .unwrap_or_else(|e| panic!("Azure {unit} fetch failed: {e}"));
    eprintln!("Azure {unit}: {} record(s)", rows.len());
    rows
}

#[tokio::test]
#[ignore = "requires live Azure credentials"]
async fn azure_health_check() {
    load_env();
    let mut cfg = azure_base();
    cfg.services.push(AzureService {
        name: "activity_log".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("azure block maps"));
    shape
        .probe()
        .await
        .expect("Azure health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live Azure credentials"]
async fn azure_fetch_activity_log() {
    azure_fetch("activity_log", HashMap::new()).await;
}

/// `entra_signins` lands tagged `azure.entra_signins`.
#[tokio::test]
#[ignore = "requires live Azure credentials"]
async fn azure_fetch_entra_signins() {
    azure_fetch("entra_signins", HashMap::new()).await;
}

/// `entra_directory_audits` lands tagged `azure.entra_directory_audits`.
#[tokio::test]
#[ignore = "requires live Azure credentials"]
async fn azure_fetch_entra_directory_audits() {
    azure_fetch("entra_directory_audits", HashMap::new()).await;
}

/// `entra_provisioning` lands tagged `azure.entra_provisioning`. A 403 when
/// the SP lacks the provisioning scope fails the test, as it should.
#[tokio::test]
#[ignore = "requires live Azure credentials AND provisioning scope on the SP"]
async fn azure_fetch_entra_provisioning() {
    azure_fetch("entra_provisioning", HashMap::new()).await;
}

/// `log_analytics` -- runs a KQL query against an existing workspace.
/// Requires the workspace ID (GUID, NOT customer-facing name) and a KQL
/// query in service config. Tenant requirement: the SP must have the
/// `Log Analytics Reader` role on the workspace.
#[tokio::test]
#[ignore = "requires live Azure credentials AND Log Analytics workspace with data"]
async fn azure_fetch_log_analytics() {
    load_env();
    let workspace_id = require("AZURE_LOG_ANALYTICS_WORKSPACE_ID");
    let kql =
        optional("AZURE_LOG_ANALYTICS_KQL").unwrap_or_else(|| "Heartbeat | take 10".to_string());
    let mut svc_config = HashMap::new();
    svc_config.insert(
        "workspace_id".into(),
        serde_json::Value::String(workspace_id),
    );
    svc_config.insert("kql".into(), serde_json::Value::String(kql));
    azure_fetch("log_analytics", svc_config).await;
}

#[tokio::test]
#[ignore = "requires live Azure credentials"]
async fn azure_fetch_sentinel() {
    load_env();
    let workspace = require("AZURE_SENTINEL_WORKSPACE_NAME");
    let resource_group = require("AZURE_SENTINEL_RESOURCE_GROUP");
    let mut svc_config = HashMap::new();
    svc_config.insert(
        "workspace_name".into(),
        serde_json::Value::String(workspace),
    );
    svc_config.insert(
        "resource_group".into(),
        serde_json::Value::String(resource_group),
    );
    azure_fetch("sentinel", svc_config).await;
}

// =============================================================================
// GCP -- service-account JWT exchange against real Cloud Logging, through
// the shipped `gcp` profile the typed `sources.gcp` block maps onto. Each
// unit is fetched off the shape as the driver would, so a refusal fails its
// own test instead of being swallowed.
// =============================================================================

fn gcp_base() -> GcpSourceConfig {
    let key_path = require("GCP_SERVICE_ACCOUNT_KEY");
    assert!(
        std::path::Path::new(&key_path).exists(),
        "GCP service account key file not found at {key_path}"
    );
    GcpSourceConfig {
        enabled: true,
        project_id: Some(require("GCP_PROJECT_ID")),
        service_account_key: Some(key_path.into()),
        credential_secret: None,
        api_url_override: None,
        token_url_override: None,
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-gcp".to_string(),
        filter: None,
    }
}

/// One unit of the gcp block as the profile fetches it, with the record
/// count and a note printed.
async fn gcp_fetch(unit: &str, note: &str) -> Vec<serde_json::Value> {
    load_env();
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: unit.to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("gcp block maps"));
    assert_eq!(
        format!("{}.{unit}", shape.connection_id()),
        format!("gcp.{unit}")
    );
    let rows = shape_rows(&shape, unit)
        .await
        .unwrap_or_else(|e| panic!("GCP {unit} fetch failed: {e}"));
    eprintln!("GCP {unit}: {} record(s){note}", rows.len());
    rows
}

#[tokio::test]
#[ignore = "requires live GCP credentials"]
async fn gcp_health_check() {
    load_env();
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: "cloud_logging".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("gcp block maps"));
    shape
        .probe()
        .await
        .expect("GCP health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live GCP credentials"]
async fn gcp_fetch_cloud_logging() {
    gcp_fetch("cloud_logging", "").await;
}

/// `admin_activity` -- ON by default in every GCP project.
#[tokio::test]
#[ignore = "requires live GCP credentials"]
async fn gcp_fetch_admin_activity() {
    gcp_fetch("admin_activity", "").await;
}

/// `data_access` -- OFF by default in GCP projects; zero records may mean
/// the tenant has not enabled Data Access audit logs.
#[tokio::test]
#[ignore = "requires live GCP credentials AND Data Access audit enabled on tenant"]
async fn gcp_fetch_data_access() {
    gcp_fetch(
        "data_access",
        " (zero may indicate tenant has not enabled Data Access audit logs)",
    )
    .await;
}

/// `system_event` -- Google-system-driven actions; usually low but non-zero
/// on any active project.
#[tokio::test]
#[ignore = "requires live GCP credentials"]
async fn gcp_fetch_system_event() {
    gcp_fetch("system_event", "").await;
}

/// `policy_denied` -- VPC SC and other policy violations; zero is normal.
#[tokio::test]
#[ignore = "requires live GCP credentials"]
async fn gcp_fetch_policy_denied() {
    gcp_fetch("policy_denied", " (zero is normal)").await;
}

/// `vpc_flow_logs` -- requires VPC Flow Logs on at least one subnet.
#[tokio::test]
#[ignore = "requires live GCP credentials AND VPC Flow Logs enabled on a subnet"]
async fn gcp_fetch_vpc_flow_logs() {
    gcp_fetch(
        "vpc_flow_logs",
        " (zero may indicate tenant has not enabled VPC Flow Logs)",
    )
    .await;
}

/// `dns_queries` -- requires a DNS server policy with logging enabled.
#[tokio::test]
#[ignore = "requires live GCP credentials AND Cloud DNS query logging enabled"]
async fn gcp_fetch_dns_queries() {
    gcp_fetch(
        "dns_queries",
        " (zero may indicate tenant has not enabled Cloud DNS query logging)",
    )
    .await;
}

/// `storage_access` -- the gcs_bucket subset of Data Access audit logs.
#[tokio::test]
#[ignore = "requires live GCP credentials AND Data Access audit enabled on tenant"]
async fn gcp_fetch_storage_access() {
    gcp_fetch("storage_access", "").await;
}

/// `scc` -- Security Command Center findings under the organisation
/// `GCP_ORGANIZATION_ID` names; the tenant must have SCC Standard or
/// Premium activated.
#[tokio::test]
#[ignore = "requires live GCP credentials AND GCP_ORGANIZATION_ID with SCC activated"]
async fn gcp_fetch_scc() {
    load_env();
    let organization = require("GCP_ORGANIZATION_ID");
    let mut cfg = gcp_base();
    cfg.services.push(GcpService {
        name: "scc".to_string(),
        config: [(
            "organization_id".to_string(),
            serde_json::Value::String(organization),
        )]
        .into_iter()
        .collect(),
    });
    let shape = builtin_shape(cfg.instances().expect("gcp block maps"));
    let rows = shape_rows(&shape, "scc")
        .await
        .expect("GCP scc fetch failed");
    eprintln!("GCP scc: {} record(s)", rows.len());
}

// =============================================================================
// M365 -- OAuth2 against the Office 365 Management Activity API + Graph,
// through the shipped `m365` profile the typed `sources.m365` block maps
// onto. Each unit is fetched off the shape as the driver would, so a
// refusal fails its own test instead of being swallowed. `.env-cloud`
// carries `M365_*`; the Azure SP (same HyperI MS tenant, both audiences
// granted) is the fallback.
// =============================================================================

fn m365_base() -> M365SourceConfig {
    let m365_or_azure = |name: &str| {
        optional(&format!("M365_{name}")).unwrap_or_else(|| require(&format!("AZURE_{name}")))
    };
    M365SourceConfig {
        enabled: true,
        tenant_id: Some(m365_or_azure("TENANT_ID")),
        client_id: Some(m365_or_azure("CLIENT_ID")),
        client_secret: Some(m365_or_azure("CLIENT_SECRET").into()),
        credential_secret: None,
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-m365".to_string(),
        filter: None,
        management_url_override: None,
        graph_url_override: None,
        token_url_override: None,
        publisher_identifier: None,
    }
}

/// One unit of the m365 block as the profile fetches it, with the record
/// count printed.
async fn m365_fetch(
    service: &str,
    config: HashMap<String, serde_json::Value>,
    unit: &str,
) -> Vec<serde_json::Value> {
    load_env();
    let mut cfg = m365_base();
    cfg.services.push(M365Service {
        name: service.to_string(),
        config,
    });
    let shape = builtin_shape(cfg.instances().expect("m365 block maps"));
    assert_eq!(
        format!("{}.{unit}", shape.connection_id()),
        format!("m365.{unit}")
    );
    let rows = shape_rows(&shape, unit)
        .await
        .unwrap_or_else(|e| panic!("M365 {unit} fetch failed: {e}"));
    eprintln!("M365 {unit}: {} record(s)", rows.len());
    rows
}

/// The Management Activity token exchange with the configured application.
#[tokio::test]
#[ignore = "requires live M365 credentials"]
async fn m365_health_check() {
    load_env();
    let mut cfg = m365_base();
    cfg.services.push(M365Service {
        name: "dlp".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("m365 block maps"));
    shape
        .probe()
        .await
        .expect("M365 health check failed with valid credentials");
}

/// `audit_log` with default content_types -- all five OMAP feeds:
/// Audit.General, Audit.AzureActiveDirectory, Audit.Exchange,
/// Audit.SharePoint, DLP.All. Each feed is its own unit tagged
/// `m365.audit_log.<feed>`; a feed the tenant refuses fails the test.
#[tokio::test]
#[ignore = "requires live M365 credentials"]
async fn m365_fetch_audit_log_all_content_types() {
    load_env();
    let mut cfg = m365_base();
    cfg.services.push(M365Service {
        name: "audit_log".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("m365 block maps"));
    let mut total = 0;
    for unit in [
        "audit_log.audit_azureactivedirectory",
        "audit_log.audit_exchange",
        "audit_log.audit_sharepoint",
        "audit_log.audit_general",
        "audit_log.dlp_all",
    ] {
        let rows = shape_rows(&shape, unit)
            .await
            .unwrap_or_else(|e| panic!("M365 {unit} fetch failed: {e}"));
        eprintln!("M365 {unit}: {} record(s)", rows.len());
        total += rows.len();
    }
    eprintln!("M365 audit_log: {total} record(s) across the five feeds");
}

/// Single-content-type opt-in: only Audit.SharePoint. The `content_types`
/// knob narrows the block to that one unit.
#[tokio::test]
#[ignore = "requires live M365 credentials"]
async fn m365_fetch_audit_log_sharepoint_only() {
    load_env();
    let mut svc_config = HashMap::new();
    svc_config.insert(
        "content_types".into(),
        serde_json::json!(["Audit.SharePoint"]),
    );
    let mut cfg = m365_base();
    cfg.services.push(M365Service {
        name: "audit_log".to_string(),
        config: svc_config,
    });
    let shape = builtin_shape(cfg.instances().expect("m365 block maps"));
    let units: Vec<&str> = shape.units().iter().map(|u| &*u.name).collect();
    assert_eq!(
        units,
        ["audit_log.audit_sharepoint"],
        "no other content type is bound"
    );
    let rows = shape_rows(&shape, "audit_log.audit_sharepoint")
        .await
        .expect("M365 audit_log[SharePoint] fetch failed");
    eprintln!("M365 audit_log[SharePoint]: {} record(s)", rows.len());
}

/// `dlp` is OMAP DLP.All: raw DLP rule-match events, tagged `m365.dlp`.
#[tokio::test]
#[ignore = "requires live M365 credentials"]
async fn m365_fetch_dlp_via_omap() {
    m365_fetch("dlp", HashMap::new(), "dlp").await;
}

/// `alerts` via Microsoft Graph alerts_v2. Requires `SecurityAlert.Read.All`
/// app permission to be granted to the SP -- if it isn't, this test fails
/// with the Graph 403, which is the desired signal.
#[tokio::test]
#[ignore = "requires live M365 credentials AND SecurityAlert.Read.All grant"]
async fn m365_fetch_alerts_via_graph() {
    m365_fetch("alerts", HashMap::new(), "alerts").await;
}

// =============================================================================
// GitHub audit log -- bearer-token PAT or GitHub App against api.github.com
//
// The typed `sources.github` block is the contract under test; the shipped
// `github` profile serves it, so the block maps onto an instance and the
// shape is driven directly. The source tag a record would carry is
// `<connection>.<unit>`, `github.audit_log` for the implicit connection.
// =============================================================================

fn github_base() -> GithubSourceConfig {
    let token = require("GITHUB_AUDIT_TOKEN");
    let org = optional("GITHUB_AUDIT_ORG");
    let enterprise = optional("GITHUB_AUDIT_ENTERPRISE");
    assert!(
        org.is_some() || enterprise.is_some(),
        "set exactly one of GITHUB_AUDIT_ORG or GITHUB_AUDIT_ENTERPRISE in .env-cloud"
    );
    GithubSourceConfig {
        enabled: true,
        org,
        enterprise,
        token: Some(token.into()),
        credential_secret: None,
        api_url_override: None,
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-github".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live GitHub credentials"]
async fn github_health_check() {
    load_env();
    let mut cfg = github_base();
    cfg.services.push(GithubService {
        name: "audit_log".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("github block maps"));
    shape
        .probe()
        .await
        .expect("GitHub health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live GitHub credentials"]
async fn github_fetch_audit_log() {
    load_env();
    let mut cfg = github_base();
    cfg.services.push(GithubService {
        name: "audit_log".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("github block maps"));
    assert_eq!(
        format!("{}.audit_log", shape.connection_id()),
        "github.audit_log"
    );
    let rows = shape_rows(&shape, "audit_log")
        .await
        .expect("GitHub audit_log fetch failed");
    eprintln!("GitHub audit_log: {} record(s)", rows.len());
}

#[tokio::test]
#[ignore = "requires live GitHub credentials"]
async fn github_fetch_audit_log_git_events_only() {
    load_env();
    let mut svc_config = HashMap::new();
    svc_config.insert("include".into(), serde_json::Value::String("git".into()));
    let mut cfg = github_base();
    cfg.services.push(GithubService {
        name: "audit_log".to_string(),
        config: svc_config,
    });
    let shape = builtin_shape(cfg.instances().expect("github block maps"));
    assert_eq!(
        format!("{}.audit_log", shape.connection_id()),
        "github.audit_log"
    );
    let rows = shape_rows(&shape, "audit_log")
        .await
        .expect("GitHub audit_log[git] fetch failed");
    eprintln!("GitHub audit_log[git]: {} record(s)", rows.len());
}

// =============================================================================
// Okta -- SSWS API token against /api/v1/logs, through the shipped `okta`
// profile the typed `sources.okta` block maps onto.
// =============================================================================

fn okta_base() -> OktaSourceConfig {
    OktaSourceConfig {
        enabled: true,
        tenant_url: Some(require("OKTA_TENANT_URL")),
        token: Some(require("OKTA_TOKEN").into()),
        use_ssws_header: optional("OKTA_USE_SSWS")
            .map(|v| matches!(v.as_str(), "1" | "true" | "TRUE" | "yes"))
            .unwrap_or(true),
        credential_secret: None,
        api_url_override: None,
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-okta".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live Okta credentials"]
async fn okta_health_check() {
    load_env();
    let mut cfg = okta_base();
    cfg.services.push(OktaService {
        name: "system_log".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("okta block maps"));
    shape
        .probe()
        .await
        .expect("Okta health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live Okta credentials"]
async fn okta_fetch_system_log() {
    load_env();
    let mut cfg = okta_base();
    cfg.services.push(OktaService {
        name: "system_log".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("okta block maps"));
    assert_eq!(
        format!("{}.system_log", shape.connection_id()),
        "okta.system_log"
    );
    let rows = shape_rows(&shape, "system_log")
        .await
        .expect("Okta system_log fetch failed");
    eprintln!("Okta system_log: {} record(s)", rows.len());
}

/// `system_log` with an OData filter applied server-side.
#[tokio::test]
#[ignore = "requires live Okta credentials"]
async fn okta_fetch_system_log_with_filter() {
    load_env();
    let mut svc_config = HashMap::new();
    svc_config.insert(
        "filter".into(),
        serde_json::Value::String(r#"eventType eq "user.session.start""#.into()),
    );
    let mut cfg = okta_base();
    cfg.services.push(OktaService {
        name: "system_log".to_string(),
        config: svc_config,
    });
    let shape = builtin_shape(cfg.instances().expect("okta block maps"));
    assert_eq!(
        format!("{}.system_log", shape.connection_id()),
        "okta.system_log"
    );
    let rows = shape_rows(&shape, "system_log")
        .await
        .expect("Okta system_log[filter] fetch failed");
    eprintln!("Okta system_log[filter]: {} record(s)", rows.len());
}

// =============================================================================
// Cloudflare -- bearer-token API against api.cloudflare.com, through the
// shipped `cloudflare` profile the typed `sources.cloudflare` block maps onto.
// =============================================================================

fn cloudflare_base() -> CloudflareSourceConfig {
    CloudflareSourceConfig {
        enabled: true,
        account_id: Some(require("CLOUDFLARE_ACCOUNT_ID")),
        token: Some(require("CLOUDFLARE_TOKEN").into()),
        credential_secret: None,
        api_url_override: None,
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-cloudflare".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live Cloudflare credentials"]
async fn cloudflare_health_check() {
    load_env();
    let mut cfg = cloudflare_base();
    cfg.services.push(CloudflareService {
        name: "audit_logs".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("cloudflare block maps"));
    shape
        .probe()
        .await
        .expect("Cloudflare health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live Cloudflare credentials"]
async fn cloudflare_fetch_audit_logs() {
    load_env();
    let mut cfg = cloudflare_base();
    cfg.services.push(CloudflareService {
        name: "audit_logs".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("cloudflare block maps"));
    assert_eq!(
        format!("{}.audit_logs", shape.connection_id()),
        "cloudflare.audit_logs"
    );
    let rows = shape_rows(&shape, "audit_logs")
        .await
        .expect("Cloudflare audit_logs fetch failed");
    eprintln!("Cloudflare audit_logs: {} record(s)", rows.len());
}

// =============================================================================
// 1Password Events Reporting -- bearer token against events.1password.com,
// through the shipped `onepassword` profile the typed `sources.onepassword`
// block maps onto.
// =============================================================================

fn onepassword_base() -> OnePasswordSourceConfig {
    OnePasswordSourceConfig {
        enabled: true,
        token: Some(require("ONEPASSWORD_EVENTS_TOKEN").into()),
        credential_secret: None,
        api_url_override: optional("ONEPASSWORD_API_BASE"),
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-onepassword".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live 1Password Business credentials"]
async fn onepassword_health_check() {
    load_env();
    let mut cfg = onepassword_base();
    cfg.services.push(OnePasswordService {
        name: "audit_events".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("onepassword block maps"));
    shape
        .probe()
        .await
        .expect("1Password health check failed with valid credentials");
}

/// One event class of the 1Password Events Reporting API through the
/// profile: the unit's rows, tagged `onepassword.<unit>`.
async fn onepassword_fetch(unit: &str) {
    load_env();
    let mut cfg = onepassword_base();
    cfg.services.push(OnePasswordService {
        name: unit.to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("onepassword block maps"));
    assert_eq!(
        format!("{}.{unit}", shape.connection_id()),
        format!("onepassword.{unit}")
    );
    let rows = shape_rows(&shape, unit)
        .await
        .unwrap_or_else(|e| panic!("1Password {unit} fetch failed: {e}"));
    eprintln!("1Password {unit}: {} record(s)", rows.len());
}

#[tokio::test]
#[ignore = "requires live 1Password Business credentials"]
async fn onepassword_fetch_signin_attempts() {
    onepassword_fetch("signin_attempts").await;
}

#[tokio::test]
#[ignore = "requires live 1Password Business credentials"]
async fn onepassword_fetch_item_usages() {
    onepassword_fetch("item_usages").await;
}

#[tokio::test]
#[ignore = "requires live 1Password Business credentials"]
async fn onepassword_fetch_audit_events() {
    onepassword_fetch("audit_events").await;
}

// =============================================================================
// CrowdStrike Falcon -- OAuth2 client_credentials against api.crowdstrike.com,
// through the shipped `crowdstrike` profile the typed `sources.crowdstrike`
// block maps onto.
// =============================================================================

fn crowdstrike_base() -> CrowdstrikeSourceConfig {
    CrowdstrikeSourceConfig {
        enabled: true,
        api_url_override: optional("CROWDSTRIKE_API_BASE"),
        client_id: Some(require("CROWDSTRIKE_CLIENT_ID")),
        client_secret: Some(require("CROWDSTRIKE_CLIENT_SECRET").into()),
        credential_secret: None,
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-crowdstrike".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live CrowdStrike Falcon credentials"]
async fn crowdstrike_health_check() {
    load_env();
    let mut cfg = crowdstrike_base();
    cfg.services.push(CrowdstrikeService {
        name: "alerts".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("crowdstrike block maps"));
    shape
        .probe()
        .await
        .expect("CrowdStrike health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live CrowdStrike Falcon credentials"]
async fn crowdstrike_fetch_alerts() {
    load_env();
    let mut cfg = crowdstrike_base();
    cfg.services.push(CrowdstrikeService {
        name: "alerts".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("crowdstrike block maps"));
    assert_eq!(
        format!("{}.alerts", shape.connection_id()),
        "crowdstrike.alerts"
    );
    let rows = shape_rows(&shape, "alerts")
        .await
        .expect("CrowdStrike alerts fetch failed");
    eprintln!("CrowdStrike alerts: {} record(s)", rows.len());
}

// =============================================================================
// Slack -- bearer-token against api.slack.com/audit/v1/logs, through the
// shipped `slack` profile the typed `sources.slack` block maps onto.
// =============================================================================

fn slack_base() -> SlackSourceConfig {
    SlackSourceConfig {
        enabled: true,
        token: Some(require("SLACK_AUDIT_TOKEN").into()),
        credential_secret: None,
        api_url_override: None,
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-slack".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live Slack Enterprise Grid credentials"]
async fn slack_health_check() {
    load_env();
    let mut cfg = slack_base();
    cfg.services.push(SlackService {
        name: "audit_logs".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("slack block maps"));
    shape
        .probe()
        .await
        .expect("Slack health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live Slack Enterprise Grid credentials"]
async fn slack_fetch_audit_logs() {
    load_env();
    let mut cfg = slack_base();
    cfg.services.push(SlackService {
        name: "audit_logs".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("slack block maps"));
    assert_eq!(
        format!("{}.audit_logs", shape.connection_id()),
        "slack.audit_logs"
    );
    let rows = shape_rows(&shape, "audit_logs")
        .await
        .expect("Slack audit_logs fetch failed");
    eprintln!("Slack audit_logs: {} record(s)", rows.len());
}

// =============================================================================
// Bitwarden -- OAuth2 client_credentials against api.bitwarden.com, through
// the shipped `bitwarden` profile the typed `sources.bitwarden` block maps
// onto.
// =============================================================================

fn bitwarden_base() -> BitwardenSourceConfig {
    BitwardenSourceConfig {
        enabled: true,
        client_id: Some(require("BITWARDEN_CLIENT_ID")),
        client_secret: Some(require("BITWARDEN_CLIENT_SECRET").into()),
        credential_secret: None,
        api_url_override: optional("BITWARDEN_API_BASE"),
        identity_url_override: optional("BITWARDEN_IDENTITY_URL"),
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-bitwarden".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live Bitwarden organisation credentials"]
async fn bitwarden_health_check() {
    load_env();
    let mut cfg = bitwarden_base();
    cfg.services.push(BitwardenService {
        name: "events".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("bitwarden block maps"));
    shape
        .probe()
        .await
        .expect("Bitwarden health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live Bitwarden organisation credentials"]
async fn bitwarden_fetch_events() {
    load_env();
    let mut cfg = bitwarden_base();
    cfg.services.push(BitwardenService {
        name: "events".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("bitwarden block maps"));
    assert_eq!(
        format!("{}.events", shape.connection_id()),
        "bitwarden.events"
    );
    let rows = shape_rows(&shape, "events")
        .await
        .expect("Bitwarden events fetch failed");
    eprintln!("Bitwarden events: {} record(s)", rows.len());
}

// =============================================================================
// Duo -- signed requests to api-XXXXXXXX.duosecurity.com, through the shipped
// `duo` profile the typed `sources.duo` block maps onto (the signing is the
// REST crate's `signature` auth mode on its `duo_v5` preset).
// =============================================================================

fn duo_base() -> DuoSourceConfig {
    DuoSourceConfig {
        enabled: true,
        api_host: Some(require("DUO_API_HOST")),
        integration_key: Some(require("DUO_INTEGRATION_KEY")),
        secret_key: Some(require("DUO_SECRET_KEY").into()),
        credential_secret: None,
        signature_version: DuoSignatureVersion::default(),
        api_url_override: None,
        interval_secs: None,
        services: vec![],
        connections: vec![],
        topic: "test-duo".to_string(),
        filter: None,
    }
}

#[tokio::test]
#[ignore = "requires live Duo Admin API credentials"]
async fn duo_health_check() {
    load_env();
    let mut cfg = duo_base();
    cfg.services.push(DuoService {
        name: "authentication_logs".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("duo block maps"));
    shape
        .probe()
        .await
        .expect("Duo health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires live Duo Admin API credentials"]
async fn duo_fetch_authentication_logs() {
    load_env();
    let mut cfg = duo_base();
    cfg.services.push(DuoService {
        name: "authentication_logs".to_string(),
        config: HashMap::new(),
    });
    let shape = builtin_shape(cfg.instances().expect("duo block maps"));
    assert_eq!(
        format!("{}.authentication_logs", shape.connection_id()),
        "duo.authentication_logs"
    );
    let rows = shape_rows(&shape, "authentication_logs")
        .await
        .expect("Duo authentication_logs fetch failed");
    eprintln!("Duo authentication_logs: {} record(s)", rows.len());
}

// =============================================================================
// Public-registry supply-chain audit -- no auth, hits public APIs.
// `#[ignore]` because they reach external services on every run.
// =============================================================================

#[tokio::test]
#[ignore = "hits public PyPI - keep out of fast test runs"]
async fn pypi_fetch_known_packages() {
    load_env();
    let mut cfg = PypiSourceConfig {
        enabled: true,
        // `pip` and `setuptools` are stable, always-present packages.
        packages: vec!["pip".to_string(), "setuptools".to_string()],
        ..PypiSourceConfig::default()
    };
    cfg.topic = "test-pypi".to_string();
    let shape = builtin_shape(cfg.instances());
    assert_eq!(
        format!("{}.metadata", shape.connection_id()),
        "pypi.metadata"
    );
    let rows = shape_rows(&shape, "metadata")
        .await
        .expect("PyPI fetch failed");
    let stamped: Vec<&str> = rows
        .iter()
        .map(|r| r["_dfe_fetcher_package"].as_str().expect("stamped"))
        .collect();
    assert_eq!(
        stamped,
        ["pip", "setuptools"],
        "one record per configured package, stamped with its name"
    );
    eprintln!("PyPI: {} record(s)", rows.len());
}

#[tokio::test]
#[ignore = "hits public crates.io - keep out of fast test runs"]
async fn crates_io_fetch_known_crates() {
    load_env();
    let mut cfg = CratesIoSourceConfig {
        enabled: true,
        // `serde` and `tokio` are stable, always-present crates.
        crates: vec!["serde".to_string(), "tokio".to_string()],
        ..CratesIoSourceConfig::default()
    };
    cfg.topic = "test-crates_io".to_string();
    let shape = builtin_shape(cfg.instances());
    assert_eq!(
        format!("{}.metadata", shape.connection_id()),
        "crates_io.metadata"
    );
    let rows = shape_rows(&shape, "metadata")
        .await
        .expect("crates.io fetch failed");
    let stamped: Vec<&str> = rows
        .iter()
        .map(|r| r["_dfe_fetcher_crate"].as_str().expect("stamped"))
        .collect();
    assert_eq!(stamped, ["serde", "tokio"]);
    eprintln!("crates.io: {} record(s)", rows.len());
}

/// One folded row for `golang.org/x/text` (a stable, always-present
/// module) off the shipped `go_modules` profile: its version list and the
/// first hundred versions' documents.
#[tokio::test]
#[ignore = "hits public Go proxy - keep out of fast test runs"]
async fn go_modules_fetch_known_module() {
    load_env();
    let cfg = GoModulesSourceConfig {
        enabled: true,
        modules: vec!["golang.org/x/text".to_string()],
        topic: "test-go_modules".to_string(),
        ..GoModulesSourceConfig::default()
    };
    let shape = builtin_shape(cfg.instances());
    assert_eq!(
        format!("{}.metadata", shape.connection_id()),
        "go_modules.metadata"
    );
    let rows = shape_rows(&shape, "metadata")
        .await
        .expect("Go proxy fetch failed");
    assert_eq!(rows.len(), 1, "one row per module");
    assert_eq!(rows[0]["_dfe_fetcher_module"], "golang.org/x/text");
    let versions = rows[0]["versions"].as_array().expect("versions");
    assert!(!versions.is_empty() && versions.len() <= 100);
    assert_eq!(
        rows[0]["version_info"]
            .as_object()
            .map(serde_json::Map::len),
        Some(versions.len()),
        "one document per listed version"
    );
    eprintln!(
        "Go modules: {} record(s), {} version(s) of golang.org/x/text",
        rows.len(),
        versions.len()
    );
}

// =============================================================================
// Google Workspace Reports API -- SPECULATIVE
// =============================================================================
//
// These tests need a Workspace tenant with:
//   1. A GCP service account with domain-wide delegation provisioned.
//   2. Reports API scope manually granted in the Admin console
//      (Security -> API controls -> Domain-wide delegation).
//   3. Admin email surfaced in env so the JWT `sub` claim impersonates it.
//
// The fetcher code is written and unit-tested; the live tests stay
// `#[ignore]`'d.

fn google_workspace_base() -> GoogleWorkspaceSourceConfig {
    GoogleWorkspaceSourceConfig {
        enabled: true,
        service_account_key: optional("GOOGLE_WORKSPACE_SA_KEY").map(Into::into),
        credential_secret: optional("GOOGLE_WORKSPACE_CREDENTIAL_SECRET"),
        admin_email: optional("GOOGLE_WORKSPACE_ADMIN_EMAIL"),
        customer_id: optional("GOOGLE_WORKSPACE_CUSTOMER_ID"),
        api_url_override: optional("GOOGLE_WORKSPACE_API_URL"),
        token_url_override: optional("GOOGLE_WORKSPACE_TOKEN_URL"),
        connections: vec![],
        topic: "test-google_workspace".to_string(),
        ..GoogleWorkspaceSourceConfig::default()
    }
}

#[tokio::test]
#[ignore = "requires a Workspace SA with domain-wide delegation + admin scope grant"]
async fn google_workspace_health_check() {
    load_env();
    let _ = require("GOOGLE_WORKSPACE_ADMIN_EMAIL");
    // SA may be supplied via key file OR vault spec; at least one is required
    if optional("GOOGLE_WORKSPACE_SA_KEY").is_none()
        && optional("GOOGLE_WORKSPACE_CREDENTIAL_SECRET").is_none()
    {
        panic!("missing GOOGLE_WORKSPACE_SA_KEY or GOOGLE_WORKSPACE_CREDENTIAL_SECRET");
    }
    let mut cfg = google_workspace_base();
    cfg.services = vec![GoogleWorkspaceService {
        name: "login".to_string(),
        config: HashMap::default(),
    }];
    let shape = builtin_shape(cfg.instances().expect("google_workspace block maps"));
    shape
        .probe()
        .await
        .expect("Workspace health check failed with valid delegation");
}

#[tokio::test]
#[ignore = "requires a Workspace SA with domain-wide delegation + admin scope grant"]
async fn google_workspace_login_activity_fetch() {
    load_env();
    let _ = require("GOOGLE_WORKSPACE_ADMIN_EMAIL");
    if optional("GOOGLE_WORKSPACE_SA_KEY").is_none()
        && optional("GOOGLE_WORKSPACE_CREDENTIAL_SECRET").is_none()
    {
        panic!("missing GOOGLE_WORKSPACE_SA_KEY or GOOGLE_WORKSPACE_CREDENTIAL_SECRET");
    }
    let mut cfg = google_workspace_base();
    cfg.services = vec![GoogleWorkspaceService {
        name: "login".to_string(),
        config: HashMap::default(),
    }];
    let shape = builtin_shape(cfg.instances().expect("google_workspace block maps"));
    assert_eq!(
        format!("{}.login", shape.connection_id()),
        "google_workspace.login"
    );
    // An empty window is valid; presence is not asserted.
    let rows = shape_rows(&shape, "login")
        .await
        .expect("Workspace login fetch failed");
    eprintln!("Workspace login: {} record(s)", rows.len());
}

// =============================================================================
// GCP Pub/Sub pull -- SPECULATIVE
// =============================================================================
//
// These tests need a GCP project with:
//   1. A Cloud Logging Log Sink routing entries into a Pub/Sub topic.
//   2. A Pub/Sub subscription on that topic.
//   3. `roles/pubsub.subscriber` granted to the fetcher SA on that
//      subscription.
//
// The fetcher code is written and unit-tested; the live tests stay
// `#[ignore]`'d.

fn gcp_pubsub_base() -> GcpPubsubSourceConfig {
    GcpPubsubSourceConfig {
        enabled: true,
        service_account_key: optional("GCP_PUBSUB_SA_KEY").map(Into::into),
        credential_secret: optional("GCP_PUBSUB_CREDENTIAL_SECRET"),
        api_url_override: optional("GCP_PUBSUB_API_URL"),
        token_url_override: optional("GCP_PUBSUB_TOKEN_URL"),
        topic: "test-gcp_pubsub".to_string(),
        ..GcpPubsubSourceConfig::default()
    }
}

/// The queue shape the block maps onto: the shipped `gcp_pubsub` profile
/// bound to the block's instance.
fn pubsub_shape(cfg: &GcpPubsubSourceConfig) -> dfe_fetcher_rest::shape::queue::QueueShape {
    let [built] = <[dfe_fetcher::config::BuiltinInstance; 1]>::try_from(
        cfg.instances().expect("gcp_pubsub block maps"),
    )
    .unwrap_or_else(|v| panic!("one connection, got {}", v.len()));
    let profile = dfe_fetcher_rest::profile::bound::resolve_profile(
        &built.instance,
        dfe_fetcher::profiles::shipped(),
    )
    .expect("a shipped profile");
    dfe_fetcher_rest::shape::RestShape::from_instance(
        &profile,
        &built.instance,
        &built.connection_id,
        dfe_fetcher_rest::http_client().expect("http client"),
        &dfe_fetcher_rest::exchange_client().expect("exchange client"),
    )
    .and_then(dfe_fetcher_rest::shape::queue::QueueShape::new)
    .unwrap_or_else(|e| panic!("bind {}: {e}", built.connection_id))
}

/// The token exchange for the Pub/Sub scope with the configured key.
#[tokio::test]
#[ignore = "requires a Pub/Sub Log Sink + subscription"]
async fn gcp_pubsub_health_check() {
    load_env();
    assert!(
        optional("GCP_PUBSUB_SA_KEY").is_some()
            || optional("GCP_PUBSUB_CREDENTIAL_SECRET").is_some(),
        "missing GCP_PUBSUB_SA_KEY or GCP_PUBSUB_CREDENTIAL_SECRET"
    );
    pubsub_shape(&gcp_pubsub_base())
        .probe()
        .await
        .expect("Pub/Sub health check failed with valid credentials");
}

/// One pull of the subscription off the queue shape: the rows the pull
/// yields, each marked with its ack id, which stay UNACKNOWLEDGED here
/// (only the driver acks, after delivery), so the broker redelivers them.
#[tokio::test]
#[ignore = "requires a Pub/Sub Log Sink + subscription"]
async fn gcp_pubsub_pull_subscription() {
    use futures::StreamExt;

    load_env();
    assert!(
        optional("GCP_PUBSUB_SA_KEY").is_some()
            || optional("GCP_PUBSUB_CREDENTIAL_SECRET").is_some(),
        "missing GCP_PUBSUB_SA_KEY or GCP_PUBSUB_CREDENTIAL_SECRET"
    );
    let project = require("GCP_PUBSUB_PROJECT_ID");
    let sub_id = require("GCP_PUBSUB_SUBSCRIPTION_ID");
    let mut cfg = gcp_pubsub_base();
    cfg.subscriptions = vec![GcpPubsubSubscription {
        project_id: project,
        subscription_id: sub_id.clone(),
        max_messages: 10,
        return_immediately: true,
    }];
    let shape = pubsub_shape(&cfg);
    let spec = shape
        .units()
        .iter()
        .find(|u| *u.name == *sub_id)
        .expect("the subscription is a unit")
        .clone();
    assert_eq!(
        format!("{}.{}", shape.rest().connection_id(), spec.name),
        format!("gcp_pubsub.{sub_id}")
    );
    let tick = dfe_fetcher_core::TickCtx {
        window: None,
        connection_id: shape.rest().connection_id(),
        unit: &spec,
        checkpoint: None,
    };
    let mut stream = shape.rows(tick);
    let mut rows = Vec::new();
    while let Some(row) = stream.next().await {
        rows.push(row.expect("Pub/Sub pull failed"));
    }
    for row in &rows {
        assert!(
            matches!(row.mark, Some(dfe_fetcher_core::Mark::Ack(_))),
            "every message carries its ack id"
        );
        let _: serde_json::Value =
            serde_json::from_slice(&row.payload).expect("each record must be valid JSON");
    }
    eprintln!(
        "Pub/Sub {sub_id}: {} record(s) pulled, none acknowledged",
        rows.len()
    );
}

// =============================================================================
// Object-store source family -- S3 backend live; GCS/Azure Blob unimplemented
// =============================================================================
//
// S3 tests use the existing AWS test credentials (.env-cloud AWS_*). To
// target a specific test bucket, set OBJECT_STORE_S3_BUCKET +
// OBJECT_STORE_S3_PREFIX (defaults pick the existing ESH_S3_BUCKET with
// an empty prefix).

fn object_store_s3_config() -> S3BackendConfig {
    S3BackendConfig {
        region: optional("OBJECT_STORE_S3_REGION")
            .or_else(|| optional("AWS_REGION"))
            .unwrap_or_else(|| "us-west-2".into()),
        endpoint_override: optional("OBJECT_STORE_S3_ENDPOINT"),
        access_key_id: Some(require("AWS_ACCESS_KEY_ID")),
        secret_access_key: Some(require("AWS_SECRET_ACCESS_KEY").into()),
        credential_secret: None,
        buckets: vec![],
    }
}

/// The block with one prefix of `format`, tagged `tag`, as the shipped
/// `object_store` profile runs it.
fn object_store_config(
    bucket: &str,
    prefix: &str,
    format: ObjectStoreFormat,
    tag: &str,
) -> ObjectStoreSourceConfig {
    let mut s3 = object_store_s3_config();
    s3.buckets = vec![ObjectStoreBucket {
        bucket: bucket.to_string(),
        prefixes: vec![ObjectStorePrefix {
            prefix: prefix.to_string(),
            format,
            source_tag: tag.to_string(),
            topic: None,
        }],
    }];
    ObjectStoreSourceConfig {
        enabled: true,
        backends: vec![ObjectStoreBackendConfig::S3(s3)],
        interval_secs: None,
        topic: "test-object_store".to_string(),
        filter: None,
    }
}

/// The signed listing of the prefix and the read of whatever it holds
/// from the last day; an empty prefix is a clean zero.
#[tokio::test]
#[ignore = "requires live AWS credentials + an S3 bucket the fetcher SA can list"]
async fn object_store_s3_list_only() {
    load_env();
    let bucket = optional("OBJECT_STORE_S3_BUCKET")
        .or_else(|| optional("ESH_S3_BUCKET"))
        .expect("set OBJECT_STORE_S3_BUCKET or ESH_S3_BUCKET in .env-cloud");
    let prefix = optional("OBJECT_STORE_S3_PREFIX").unwrap_or_default();
    let cfg = object_store_config(&bucket, &prefix, ObjectStoreFormat::Jsonl, "smoke_test");
    let shape = builtin_shape(cfg.instances().expect("object_store block maps"));
    assert_eq!(
        format!("{}.smoke_test", shape.connection_id()),
        "object_store.smoke_test"
    );
    let rows = shape_rows(&shape, "smoke_test")
        .await
        .expect("object_store listing or read failed");
    eprintln!(
        "object_store s3({bucket}/{prefix}): {} record(s)",
        rows.len()
    );
}

#[tokio::test]
#[ignore = "requires AWS credentials AND an S3 prefix with at least one gzipped JSON-lines object"]
async fn object_store_s3_parse_json_gz_objects() {
    load_env();
    let bucket = require("OBJECT_STORE_S3_BUCKET");
    let prefix = require("OBJECT_STORE_S3_PREFIX");
    let cfg = object_store_config(
        &bucket,
        &prefix,
        ObjectStoreFormat::JsonGz,
        "smoke_test_json_gz",
    );
    let shape = builtin_shape(cfg.instances().expect("object_store block maps"));
    let rows = shape_rows(&shape, "smoke_test_json_gz")
        .await
        .expect("object_store listing or read failed");
    eprintln!(
        "object_store s3({bucket}/{prefix}) json_gz: {} record(s)",
        rows.len()
    );
    for row in &rows {
        assert_eq!(
            row["_dfe_fetcher_object"]["bucket"],
            bucket.as_str(),
            "every record carries the envelope"
        );
    }
}

// =============================================================================
// Salesforce -- SetupAuditTrail + LoginHistory (SOQL) + EventLogFile (CSV)
// =============================================================================
//
// Auth picks JWT bearer when SALESFORCE_PRIVATE_KEY[_PATH] is set, else
// client credentials via SALESFORCE_CLIENT_SECRET. Requires a connected app
// in the target org + an integration user with API Enabled, View Setup Audit
// Trail, and (for event_log_file) View Event Log Files.

fn salesforce_base() -> SalesforceSourceConfig {
    SalesforceSourceConfig {
        enabled: true,
        login_url: optional("SALESFORCE_LOGIN_URL"),
        api_version: optional("SALESFORCE_API_VERSION"),
        client_id: optional("SALESFORCE_CLIENT_ID"),
        username: optional("SALESFORCE_USERNAME"),
        private_key: optional("SALESFORCE_PRIVATE_KEY").map(Into::into),
        private_key_secret: optional("SALESFORCE_PRIVATE_KEY_SECRET"),
        client_secret: optional("SALESFORCE_CLIENT_SECRET").map(Into::into),
        credential_secret: optional("SALESFORCE_CREDENTIAL_SECRET"),
        instance_url_override: optional("SALESFORCE_INSTANCE_URL"),
        connections: vec![],
        topic: "test-salesforce".to_string(),
        ..SalesforceSourceConfig::default()
    }
}

fn salesforce_has_auth() -> bool {
    optional("SALESFORCE_CLIENT_ID").is_some()
        && (optional("SALESFORCE_PRIVATE_KEY").is_some()
            || optional("SALESFORCE_PRIVATE_KEY_SECRET").is_some()
            || optional("SALESFORCE_CLIENT_SECRET").is_some()
            || optional("SALESFORCE_CREDENTIAL_SECRET").is_some())
}

/// One unit of the salesforce block as the profile fetches it, with the
/// record count printed.
async fn salesforce_fetch(unit: &str) -> Vec<serde_json::Value> {
    load_env();
    assert!(salesforce_has_auth(), "missing Salesforce auth env vars");
    let mut cfg = salesforce_base();
    cfg.services = vec![SalesforceService {
        name: unit.to_string(),
        config: HashMap::new(),
    }];
    let shape = builtin_shape(cfg.instances().expect("salesforce block maps"));
    assert_eq!(
        format!("{}.{unit}", shape.connection_id()),
        format!("salesforce.{unit}")
    );
    let rows = shape_rows(&shape, unit)
        .await
        .unwrap_or_else(|e| panic!("Salesforce {unit} fetch failed: {e}"));
    eprintln!("Salesforce {unit}: {} record(s)", rows.len());
    rows
}

/// The token exchange (JWT bearer or client credentials) with the
/// configured connected app.
#[tokio::test]
#[ignore = "requires a Salesforce connected app + integration user"]
async fn salesforce_health_check() {
    load_env();
    assert!(
        salesforce_has_auth(),
        "missing SALESFORCE_CLIENT_ID + one of SALESFORCE_PRIVATE_KEY / \
         SALESFORCE_PRIVATE_KEY_SECRET / SALESFORCE_CLIENT_SECRET / \
         SALESFORCE_CREDENTIAL_SECRET"
    );
    let mut cfg = salesforce_base();
    cfg.services = vec![SalesforceService {
        name: "login_history".to_string(),
        config: HashMap::new(),
    }];
    let shape = builtin_shape(cfg.instances().expect("salesforce block maps"));
    shape
        .probe()
        .await
        .expect("Salesforce health check failed with valid credentials");
}

#[tokio::test]
#[ignore = "requires a Salesforce connected app + integration user"]
async fn salesforce_setup_audit_trail_and_login_history() {
    salesforce_fetch("setup_audit_trail").await;
    salesforce_fetch("login_history").await;
}

#[tokio::test]
#[ignore = "requires Salesforce Event Monitoring (or the 7 free EventLogFile types)"]
async fn salesforce_event_log_file() {
    let rows = salesforce_fetch("event_log_file").await;
    for row in &rows {
        assert!(
            row["_dfe_fetcher_event_type"].is_string(),
            "ELF record missing _dfe_fetcher_event_type envelope"
        );
    }
}
