#!/usr/bin/env python3
"""Generate .env from terraform output -json.

Usage:
    terraform output -json | python3 gen-env.py > ../../.env
"""

import base64
import json
import os
import sys


def main():
    data = json.load(sys.stdin)

    def val(key, default=""):
        entry = data.get(key)
        if entry is None:
            return default
        return entry["value"]

    lines = [
        "# Auto-generated by infra/test/gen-env.py -- do not edit manually",
        "# Regenerate: cd infra/test && terraform output -json | python3 gen-env.py > ../../.env",
        "",
        "# AWS",
        f'AWS_ACCESS_KEY_ID="{val("aws_access_key_id")}"',
        f'AWS_SECRET_ACCESS_KEY="{val("aws_secret_access_key")}"',
        f'AWS_REGION="{val("aws_region")}"',
        "",
        "# Azure",
        f'AZURE_TENANT_ID="{val("azure_tenant_id")}"',
        f'AZURE_CLIENT_ID="{val("azure_client_id")}"',
        f'AZURE_CLIENT_SECRET="{val("azure_client_secret")}"',
        f'AZURE_SUBSCRIPTION_ID="{val("azure_subscription_id")}"',
        "",
        "# M365",
        f'M365_TENANT_ID="{val("m365_tenant_id")}"',
        f'M365_CLIENT_ID="{val("m365_client_id")}"',
        f'M365_CLIENT_SECRET="{val("m365_client_secret")}"',
        "",
        "# GCP",
        f'GCP_PROJECT_ID="{val("gcp_project_id")}"',
    ]

    # Write GCP service account key to .tmp/ if present
    gcp_key_b64 = val("gcp_service_account_key")
    if gcp_key_b64:
        gcp_key_json = base64.b64decode(gcp_key_b64).decode()
        tmp_dir = os.path.join(os.path.dirname(__file__), "..", "..", ".tmp")
        os.makedirs(tmp_dir, exist_ok=True)
        key_path = os.path.join(tmp_dir, "gcp-sa-key.json")
        with open(key_path, "w") as f:
            f.write(gcp_key_json)
        os.chmod(key_path, 0o600)
        lines.append('GCP_SERVICE_ACCOUNT_KEY=".tmp/gcp-sa-key.json"')
        print(f"# GCP key written to {key_path}", file=sys.stderr)
    else:
        lines.append(
            "# GCP_SERVICE_ACCOUNT_KEY not yet provisioned -- re-run after GCP auth"
        )
        print(
            "# GCP key not available (GCP resources not yet provisioned)",
            file=sys.stderr,
        )

    print("\n".join(lines))


if __name__ == "__main__":
    main()
